// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package barrieroperator

// <no value>

type BarrierOperatorGet struct {
}

func (cmd *BarrierOperatorGet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *BarrierOperatorGet) MarshalBinary() (payload []byte, err error) {

	return
}
