// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package barrieroperator

// <no value>

type BarrierOperatorSignalSupportedGet struct {
}

func (cmd *BarrierOperatorSignalSupportedGet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *BarrierOperatorSignalSupportedGet) MarshalBinary() (payload []byte, err error) {

	return
}
