// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package barrieroperator

// <no value>

type BarrierOperatorSignalSupportedGet struct {
}

func ParseBarrierOperatorSignalSupportedGet(payload []byte) BarrierOperatorSignalSupportedGet {
	val := BarrierOperatorSignalSupportedGet{}

	return val
}
