// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package barrieroperator

import "errors"

// <no value>

type BarrierOperatorSignalGet struct {
	SubsystemType byte
}

func (cmd *BarrierOperatorSignalGet) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SubsystemType = payload[i]
	i++

	return nil
}
