// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package association

import "errors"

// <no value>

type AssociationGet struct {
	GroupingIdentifier byte
}

func (cmd *AssociationGet) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.GroupingIdentifier = payload[i]
	i++

	return nil
}

func (cmd *AssociationGet) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.GroupingIdentifier)

	return
}
