// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package association

import "errors"

// <no value>

type AssociationSet struct {
	GroupingIdentifier byte

	NodeId []byte
}

func (cmd *AssociationSet) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.GroupingIdentifier = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NodeId = payload[i:]

	return nil
}

func (cmd *AssociationSet) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.GroupingIdentifier)

	payload = append(payload, cmd.NodeId...)

	return
}
