// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package usercode

import (
	"encoding/gob"
	"errors"
)

func init() {
	gob.Register(UserCodeGet{})
}

// <no value>
type UserCodeGet struct {
	UserIdentifier byte
}

func (cmd *UserCodeGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.UserIdentifier = payload[i]
	i++

	return nil
}

func (cmd *UserCodeGet) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.UserIdentifier)

	return
}
