// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package usercode

// <no value>

type UsersNumberReport struct {
	SupportedUsers byte
}

func ParseUsersNumberReport(payload []byte) UsersNumberReport {
	val := UsersNumberReport{}

	i := 2

	val.SupportedUsers = payload[i]
	i++

	return val
}
