// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package usercode

// <no value>

type UsersNumberGet struct {
}

func (cmd *UsersNumberGet) UnmarshalBinary(payload []byte) error {

	return nil
}
