// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package multichannelassociationv2

// <no value>

type MultiChannelAssociationGet struct {
	GroupingIdentifier byte
}

func ParseMultiChannelAssociationGet(payload []byte) MultiChannelAssociationGet {
	val := MultiChannelAssociationGet{}

	i := 2

	val.GroupingIdentifier = payload[i]
	i++

	return val
}
