// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package multichannelassociationv2

// <no value>

type MultiChannelAssociationGroupingsGet struct {
}

func ParseMultiChannelAssociationGroupingsGet(payload []byte) MultiChannelAssociationGroupingsGet {
	val := MultiChannelAssociationGroupingsGet{}

	return val
}
