// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package scheduleentrylockv2

// <no value>

type ScheduleEntryLockEnableAllSet struct {
	Enabled byte
}

func ParseScheduleEntryLockEnableAllSet(payload []byte) ScheduleEntryLockEnableAllSet {
	val := ScheduleEntryLockEnableAllSet{}

	i := 2

	val.Enabled = payload[i]
	i++

	return val
}
