// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package scheduleentrylockv2

// <no value>

type ScheduleEntryLockTimeOffsetGet struct {
}

func (cmd *ScheduleEntryLockTimeOffsetGet) UnmarshalBinary(payload []byte) error {

	return nil
}
