// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package thermostatsetpointv3

import "errors"

// <no value>

type ThermostatSetpointReport struct {
	Level struct {
		SetpointType byte
	}

	Level2 struct {
		Size byte

		Scale byte

		Precision byte
	}

	Value []byte
}

func (cmd *ThermostatSetpointReport) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Level.SetpointType = (payload[i] & 0x0F)

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Level2.Size = (payload[i] & 0x07)

	cmd.Level2.Scale = (payload[i] & 0x18) << 3

	cmd.Level2.Precision = (payload[i] & 0xE0) << 5

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Value = payload[i : i+1]
	i += 1

	return nil
}
