// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package thermostatsetpointv3

// <no value>

type ThermostatSetpointSupportedGet struct {
}

func ParseThermostatSetpointSupportedGet(payload []byte) ThermostatSetpointSupportedGet {
	val := ThermostatSetpointSupportedGet{}

	return val
}
