// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchall

// <no value>

type SwitchAllGet struct {
}

func ParseSwitchAllGet(payload []byte) SwitchAllGet {
	val := SwitchAllGet{}

	return val
}
