// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchall

import "encoding/gob"

func init() {
	gob.Register(On{})
}

// <no value>
type On struct {
}

func (cmd On) CommandClassID() byte {
	return 0x27
}

func (cmd On) CommandID() byte {
	return byte(CommandOn)
}

func (cmd *On) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *On) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = cmd.CommandClassID()
	payload[1] = cmd.CommandID()

	return
}
