// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchall

// <no value>

type SwitchAllOn struct {
}

func ParseSwitchAllOn(payload []byte) SwitchAllOn {
	val := SwitchAllOn{}

	return val
}
