// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package basictariffinfo

// <no value>

type BasicTariffInfoGet struct {
}

func ParseBasicTariffInfoGet(payload []byte) BasicTariffInfoGet {
	val := BasicTariffInfoGet{}

	return val
}
