// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package sensormultilevelv6

import (
	"encoding/gob"

	"github.com/helioslabs/gozw/command-class"
)

const CommandSupportedGetSensor commandclass.CommandID = 0x01

func init() {
	gob.Register(SupportedGetSensor{})
	commandclass.Register(commandclass.CommandIdentifier{
		CommandClass: commandclass.CommandClassID(0x31),
		Command:      commandclass.CommandID(0x01),
		Version:      6,
	}, NewSupportedGetSensor)
}

func NewSupportedGetSensor() commandclass.Command {
	return &SupportedGetSensor{}
}

// <no value>
type SupportedGetSensor struct {
}

func (cmd SupportedGetSensor) CommandClassID() commandclass.CommandClassID {
	return 0x31
}

func (cmd SupportedGetSensor) CommandID() commandclass.CommandID {
	return CommandSupportedGetSensor
}

func (cmd SupportedGetSensor) CommandIDString() string {
	return "SENSOR_MULTILEVEL_SUPPORTED_GET_SENSOR"
}

func (cmd *SupportedGetSensor) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *SupportedGetSensor) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
