// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package hrvcontrol

// <no value>

type HrvControlModeSupportedGet struct {
}

func ParseHrvControlModeSupportedGet(payload []byte) HrvControlModeSupportedGet {
	val := HrvControlModeSupportedGet{}

	return val
}
