// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package hrvcontrol

import "encoding/gob"

func init() {
	gob.Register(HrvControlModeGet{})
}

// <no value>
type HrvControlModeGet struct {
}

func (cmd *HrvControlModeGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)

	return nil
}

func (cmd *HrvControlModeGet) MarshalBinary() (payload []byte, err error) {

	return
}
