// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package hrvcontrol

// <no value>

type HrvControlModeGet struct {
}

func ParseHrvControlModeGet(payload []byte) HrvControlModeGet {
	val := HrvControlModeGet{}

	return val
}
