// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package hrvcontrol

import "errors"

// <no value>

type HrvControlModeSet struct {
	Properties1 struct {
		Mode byte
	}
}

func (cmd *HrvControlModeSet) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.Mode = (payload[i] & 0x1F)

	i += 1

	return nil
}

func (cmd *HrvControlModeSet) MarshalBinary() (payload []byte, err error) {

	{
		var val byte

		val |= (cmd.Properties1.Mode) & byte(0x1F)

		payload = append(payload, val)
	}

	return
}
