// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package hrvcontrol

// <no value>

type HrvControlModeGet struct {
}

func (cmd *HrvControlModeGet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *HrvControlModeGet) MarshalBinary() (payload []byte, err error) {

	return
}
