// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchall

import "encoding/gob"

func init() {
	gob.Register(Off{})
}

// <no value>
type Off struct {
}

func (cmd Off) CommandClassID() byte {
	return 0x27
}

func (cmd Off) CommandID() byte {
	return byte(CommandOff)
}

func (cmd *Off) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *Off) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = cmd.CommandClassID()
	payload[1] = cmd.CommandID()

	return
}
