// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchmultilevelv3

import "errors"

// <no value>

type SwitchMultilevelReport struct {
	Value byte
}

func (cmd *SwitchMultilevelReport) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Value = payload[i]
	i++

	return nil
}

func (cmd *SwitchMultilevelReport) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.Value)

	return
}
