// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchmultilevelv3

import "errors"

// <no value>

type SwitchMultilevelStartLevelChange struct {
	Properties1 struct {
		IgnoreStartLevel bool

		IncDec byte

		UpDown byte
	}

	StartLevel byte

	DimmingDuration byte

	StepSize byte
}

func (cmd *SwitchMultilevelStartLevelChange) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.IncDec = (payload[i] & 0x18) << 3

	cmd.Properties1.UpDown = (payload[i] & 0xC0) << 6

	if payload[i]&0x20 == 0x20 {
		cmd.Properties1.IgnoreStartLevel = true
	} else {
		cmd.Properties1.IgnoreStartLevel = false
	}

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.StartLevel = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.DimmingDuration = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.StepSize = payload[i]
	i++

	return nil
}
