// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchmultilevelv3

// <no value>

type SwitchMultilevelStopLevelChange struct {
}

func (cmd *SwitchMultilevelStopLevelChange) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *SwitchMultilevelStopLevelChange) MarshalBinary() (payload []byte, err error) {

	return
}
