// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchmultilevelv3

// <no value>

type SwitchMultilevelSupportedReport struct {
	Properties1 struct {
		PrimarySwitchType byte
	}

	Properties2 struct {
		SecondarySwitchType byte
	}
}

func ParseSwitchMultilevelSupportedReport(payload []byte) SwitchMultilevelSupportedReport {
	val := SwitchMultilevelSupportedReport{}

	i := 2

	val.Properties1.PrimarySwitchType = (payload[i] & 0x1F)

	i += 1

	val.Properties2.SecondarySwitchType = (payload[i] & 0x1F)

	i += 1

	return val
}
