// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package configuration

// <no value>

type ConfigurationGet struct {
	ParameterNumber byte
}

func ParseConfigurationGet(payload []byte) ConfigurationGet {
	val := ConfigurationGet{}

	i := 2

	val.ParameterNumber = payload[i]
	i++

	return val
}
