// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package configuration

import "errors"

// <no value>

type ConfigurationSet struct {
	ParameterNumber byte

	Level struct {
		Size byte

		Default bool
	}

	ConfigurationValue []byte
}

func (cmd *ConfigurationSet) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ParameterNumber = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Level.Size = (payload[i] & 0x07)

	if payload[i]&0x80 == 0x80 {
		cmd.Level.Default = true
	} else {
		cmd.Level.Default = false
	}

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ConfigurationValue = payload[i : i+1]
	i += 1

	return nil
}
