// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package nodenaming

// <no value>

type NodeNamingNodeLocationSet struct {
	CharPresentation byte

	NodeLocationChar string
}

func ParseNodeNamingNodeLocationSet(payload []byte) NodeNamingNodeLocationSet {
	val := NodeNamingNodeLocationSet{}

	i := 2

	val.CharPresentation = (payload[i] & 0x07)

	i += 1

	val.NodeLocationChar = string(payload[i : i+16])

	i += 16

	return val
}
