// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package nodenaming

import (
	"encoding/gob"
	"errors"
)

func init() {
	gob.Register(NodeNamingNodeLocationReport{})
}

// <no value>
type NodeNamingNodeLocationReport struct {
	Level struct {
		CharPresentation byte
	}

	NodeLocationChar string
}

func (cmd *NodeNamingNodeLocationReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Level.CharPresentation = (payload[i] & 0x07)

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NodeLocationChar = string(payload[i : i+16])

	i += 16

	return nil
}

func (cmd *NodeNamingNodeLocationReport) MarshalBinary() (payload []byte, err error) {

	{
		var val byte

		val |= (cmd.Level.CharPresentation) & byte(0x07)

		payload = append(payload, val)
	}

	if paramLen := len(cmd.NodeLocationChar); paramLen > 16 {
		return nil, errors.New("Length overflow in array parameter NodeLocationChar")
	}

	payload = append(payload, []byte(cmd.NodeLocationChar)...)

	return
}
