// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package thermostatfanmode

import "errors"

// <no value>

type ThermostatFanModeSet struct {
	Level struct {
		FanMode byte
	}
}

func (cmd *ThermostatFanModeSet) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Level.FanMode = (payload[i] & 0x0F)

	i += 1

	return nil
}

func (cmd *ThermostatFanModeSet) MarshalBinary() (payload []byte, err error) {

	{
		var val byte

		val |= (cmd.Level.FanMode) & byte(0x0F)

		payload = append(payload, val)
	}

	return
}
