// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package thermostatfanmode

// <no value>

type ThermostatFanModeSet struct {
	FanMode byte
}

func ParseThermostatFanModeSet(payload []byte) ThermostatFanModeSet {
	val := ThermostatFanModeSet{}

	i := 2

	val.FanMode = (payload[i] & 0x0F)

	i += 1

	return val
}
