// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package thermostatfanmode

// <no value>

type ThermostatFanModeSupportedGet struct {
}

func (cmd *ThermostatFanModeSupportedGet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *ThermostatFanModeSupportedGet) MarshalBinary() (payload []byte, err error) {

	return
}
