// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package thermostatfanmode

// <no value>

type ThermostatFanModeSupportedReport struct {
	BitMask byte
}

func ParseThermostatFanModeSupportedReport(payload []byte) ThermostatFanModeSupportedReport {
	val := ThermostatFanModeSupportedReport{}

	i := 2

	val.BitMask = payload[i]
	i++

	return val
}
