// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package simpleavcontrol

import "encoding/gob"

func init() {
	gob.Register(SimpleAvControlGet{})
}

// <no value>
type SimpleAvControlGet struct {
}

func (cmd *SimpleAvControlGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)

	return nil
}

func (cmd *SimpleAvControlGet) MarshalBinary() (payload []byte, err error) {

	return
}
