// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package simpleavcontrol

// <no value>

type SimpleAvControlReport struct {
	NumberOfReports byte
}

func ParseSimpleAvControlReport(payload []byte) SimpleAvControlReport {
	val := SimpleAvControlReport{}

	i := 2

	val.NumberOfReports = payload[i]
	i++

	return val
}
