// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package nodenaming

import (
	"encoding/gob"
	"errors"

	"github.com/helioslabs/gozw/command-class"
)

const CommandNodeNameReport commandclass.CommandID = 0x03

func init() {
	gob.Register(NodeNameReport{})
	commandclass.Register(commandclass.CommandIdentifier{
		CommandClass: commandclass.CommandClassID(0x77),
		Command:      commandclass.CommandID(0x03),
		Version:      1,
	}, NewNodeNameReport)
}

func NewNodeNameReport() commandclass.Command {
	return &NodeNameReport{}
}

// <no value>
type NodeNameReport struct {
	Level struct {
		CharPresentation byte
	}

	NodeNameChar string
}

func (cmd NodeNameReport) CommandClassID() commandclass.CommandClassID {
	return 0x77
}

func (cmd NodeNameReport) CommandID() commandclass.CommandID {
	return CommandNodeNameReport
}

func (cmd NodeNameReport) CommandIDString() string {
	return "NODE_NAMING_NODE_NAME_REPORT"
}

func (cmd *NodeNameReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Level.CharPresentation = (payload[i] & 0x07)

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NodeNameChar = string(payload[i : i+16])

	i += 16

	return nil
}

func (cmd *NodeNameReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	{
		var val byte

		val |= (cmd.Level.CharPresentation) & byte(0x07)

		payload = append(payload, val)
	}

	if paramLen := len(cmd.NodeNameChar); paramLen > 16 {
		return nil, errors.New("Length overflow in array parameter NodeNameChar")
	}

	payload = append(payload, []byte(cmd.NodeNameChar)...)

	return
}
