.PHONY: test

lint:
	go install ./...
	gometalinter ./...

test:
	go install ./...
	gometalinter -D golint -D errcheck -D gocyclo -D dupl ./...
	env GOMAXPROCS=8 go test -cover ./zwave/...

install-tools:
	go get github.com/alecthomas/gometalinter
	gometalinter --install --update
