// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package meterv2

import "encoding/binary"

// <no value>

type MeterReport struct {
	MeterType byte

	RateType byte

	Size byte

	Scale byte

	Precision byte

	MeterValue []byte

	DeltaTime uint16

	PreviousMeterValue []byte
}

func ParseMeterReport(payload []byte) MeterReport {
	val := MeterReport{}

	i := 2

	val.MeterType = (payload[i] & 0x1F)

	val.RateType = (payload[i] & 0x60) << 5

	i += 1

	val.Size = (payload[i] & 0x07)

	val.Scale = (payload[i] & 0x18) << 3

	val.Precision = (payload[i] & 0xE0) << 5

	i += 1

	val.MeterValue = payload[i : i+1]
	i += 1

	val.DeltaTime = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	val.PreviousMeterValue = payload[i : i+1]
	i += 1

	return val
}
