// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package meterv2

import "errors"

// <no value>

type MeterSupportedReport struct {
	Properties1 struct {
		MeterType byte

		MeterReset bool
	}

	Properties2 struct {
		ScaleSupported byte
	}
}

func (cmd *MeterSupportedReport) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.MeterType = (payload[i] & 0x1F)

	if payload[i]&0x80 == 0x80 {
		cmd.Properties1.MeterReset = true
	} else {
		cmd.Properties1.MeterReset = false
	}

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties2.ScaleSupported = (payload[i] & 0x0F)

	i += 1

	return nil
}

func (cmd *MeterSupportedReport) MarshalBinary() (payload []byte, err error) {

	{
		var val byte

		val |= (cmd.Properties1.MeterType) & byte(0x1F)

		if cmd.Properties1.MeterReset {
			val |= byte(0x80) // flip bits on
		} else {
			val &= ^byte(0x80) // flip bits off
		}

		payload = append(payload, val)
	}

	{
		var val byte

		val |= (cmd.Properties2.ScaleSupported) & byte(0x0F)

		payload = append(payload, val)
	}

	return
}
