// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchtogglebinary

// <no value>

type SwitchToggleBinaryReport struct {
	Value byte
}

func ParseSwitchToggleBinaryReport(payload []byte) SwitchToggleBinaryReport {
	val := SwitchToggleBinaryReport{}

	i := 2

	val.Value = payload[i]
	i++

	return val
}
