// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchtogglebinary

// <no value>

type SwitchToggleBinarySet struct {
}

func (cmd *SwitchToggleBinarySet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *SwitchToggleBinarySet) MarshalBinary() (payload []byte, err error) {

	return
}
