// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package geographiclocation

// <no value>

type GeographicLocationGet struct {
}

func ParseGeographicLocationGet(payload []byte) GeographicLocationGet {
	val := GeographicLocationGet{}

	return val
}
