// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package geographiclocation

import "errors"

// <no value>

type GeographicLocationReport struct {
	LongitudeDegrees byte

	Level struct {
		LongitudeMinutes byte

		LongSign bool
	}

	LatitudeDegrees byte

	Level2 struct {
		LatitudeMinutes byte

		LatSign bool
	}
}

func (cmd *GeographicLocationReport) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.LongitudeDegrees = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Level.LongitudeMinutes = (payload[i] & 0x7F)

	if payload[i]&0x80 == 0x80 {
		cmd.Level.LongSign = true
	} else {
		cmd.Level.LongSign = false
	}

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.LatitudeDegrees = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Level2.LatitudeMinutes = (payload[i] & 0x7F)

	if payload[i]&0x80 == 0x80 {
		cmd.Level2.LatSign = true
	} else {
		cmd.Level2.LatSign = false
	}

	i += 1

	return nil
}
