// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package geographiclocation

// <no value>

type GeographicLocationReport struct {
	LongitudeDegrees byte

	LongitudeMinutes byte

	LongSign bool

	LatitudeDegrees byte

	LatitudeMinutes byte

	LatSign bool
}

func ParseGeographicLocationReport(payload []byte) GeographicLocationReport {
	val := GeographicLocationReport{}

	i := 2

	val.LongitudeDegrees = payload[i]
	i++

	val.LongitudeMinutes = (payload[i] & 0x7F)

	if payload[i]&0x80 == 0x80 {
		val.LongSign = true
	} else {
		val.LongSign = false
	}

	i += 1

	val.LatitudeDegrees = payload[i]
	i++

	val.LatitudeMinutes = (payload[i] & 0x7F)

	if payload[i]&0x80 == 0x80 {
		val.LatSign = true
	} else {
		val.LatSign = false
	}

	i += 1

	return val
}
