// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package clock

import "errors"

// <no value>

type ClockReport struct {
	Level struct {
		Hour byte

		Weekday byte
	}

	Minute byte
}

func (cmd *ClockReport) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Level.Hour = (payload[i] & 0x1F)

	cmd.Level.Weekday = (payload[i] & 0xE0) << 5

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Minute = payload[i]
	i++

	return nil
}
