// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package alarmv2

// <no value>

type AlarmTypeSupportedGet struct {
}

func ParseAlarmTypeSupportedGet(payload []byte) AlarmTypeSupportedGet {
	val := AlarmTypeSupportedGet{}

	return val
}
