// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package manufacturerspecific

import "encoding/binary"

// <no value>

type ManufacturerSpecificReport struct {
	ManufacturerId uint16

	ProductTypeId uint16

	ProductId uint16
}

func ParseManufacturerSpecificReport(payload []byte) ManufacturerSpecificReport {
	val := ManufacturerSpecificReport{}

	i := 2

	val.ManufacturerId = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	val.ProductTypeId = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	val.ProductId = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	return val
}
