// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package networkmanagementproxy

import "errors"

// <no value>

type NodeInfoCachedGet struct {
	SeqNo byte

	Properties1 struct {
		MaxAge byte
	}

	NodeId byte
}

func (cmd *NodeInfoCachedGet) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SeqNo = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.MaxAge = (payload[i] & 0x0F)

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NodeId = payload[i]
	i++

	return nil
}

func (cmd *NodeInfoCachedGet) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.SeqNo)

	{
		var val byte

		val |= (cmd.Properties1.MaxAge) & byte(0x0F)

		payload = append(payload, val)
	}

	payload = append(payload, cmd.NodeId)

	return
}
