// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package networkmanagementinclusion

// <no value>

type FailedNodeRemove struct {
	SeqNo byte

	NodeId byte
}

func ParseFailedNodeRemove(payload []byte) FailedNodeRemove {
	val := FailedNodeRemove{}

	i := 2

	val.SeqNo = payload[i]
	i++

	val.NodeId = payload[i]
	i++

	return val
}
