// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package networkmanagementinclusion

// <no value>

type FailedNodeReplace struct {
	SeqNo byte

	NodeId byte

	TxOptions byte

	Mode byte
}

func ParseFailedNodeReplace(payload []byte) FailedNodeReplace {
	val := FailedNodeReplace{}

	i := 2

	val.SeqNo = payload[i]
	i++

	val.NodeId = payload[i]
	i++

	val.TxOptions = payload[i]
	i++

	val.Mode = payload[i]
	i++

	return val
}
