// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package networkmanagementinclusion

// <no value>

type NodeRemoveStatus struct {
	SeqNo byte

	Status byte

	Nodeid byte
}

func ParseNodeRemoveStatus(payload []byte) NodeRemoveStatus {
	val := NodeRemoveStatus{}

	i := 2

	val.SeqNo = payload[i]
	i++

	val.Status = payload[i]
	i++

	val.Nodeid = payload[i]
	i++

	return val
}
