// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package networkmanagementinclusion

// <no value>

type NodeAdd struct {
	SeqNo byte

	Mode byte

	TxOptions byte
}

func ParseNodeAdd(payload []byte) NodeAdd {
	val := NodeAdd{}

	i := 2

	val.SeqNo = payload[i]
	i++

	val.Mode = payload[i]
	i++

	val.TxOptions = payload[i]
	i++

	return val
}
