// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package networkmanagementinclusion

import "errors"

// <no value>

type ReturnRouteAssign struct {
	SeqNo byte

	SourceNodeId byte

	DestinationNodeId byte
}

func (cmd *ReturnRouteAssign) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SeqNo = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SourceNodeId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.DestinationNodeId = payload[i]
	i++

	return nil
}

func (cmd *ReturnRouteAssign) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.SeqNo)

	payload = append(payload, cmd.SourceNodeId)

	payload = append(payload, cmd.DestinationNodeId)

	return
}
