// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package doorlocklogging

import "encoding/gob"

func init() {
	gob.Register(RecordsSupportedGet{})
}

// <no value>
type RecordsSupportedGet struct {
}

func (cmd RecordsSupportedGet) CommandClassID() byte {
	return 0x4C
}

func (cmd RecordsSupportedGet) CommandID() byte {
	return byte(CommandRecordsSupportedGet)
}

func (cmd *RecordsSupportedGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *RecordsSupportedGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = cmd.CommandClassID()
	payload[1] = cmd.CommandID()

	return
}
