// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package doorlocklogging

import "encoding/binary"

// <no value>

type RecordReport struct {
	RecordNumber byte

	Year uint16

	Month byte

	Day byte

	HourLocalTime byte

	RecordStatus byte

	MinuteLocalTime byte

	SecondLocalTime byte

	EventType byte

	UserIdentifier byte

	UserCodeLength byte

	UserCode []byte
}

func ParseRecordReport(payload []byte) RecordReport {
	val := RecordReport{}

	i := 2

	val.RecordNumber = payload[i]
	i++

	val.Year = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	val.Month = payload[i]
	i++

	val.Day = payload[i]
	i++

	val.HourLocalTime = (payload[i] & 0x1F)

	val.RecordStatus = (payload[i] & 0xE0) << 5

	i += 1

	val.MinuteLocalTime = payload[i]
	i++

	val.SecondLocalTime = payload[i]
	i++

	val.EventType = payload[i]
	i++

	val.UserIdentifier = payload[i]
	i++

	val.UserCodeLength = payload[i]
	i++

	val.UserCode = payload[i:]

	return val
}
