// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package metertblconfig

// <no value>

type MeterTblTablePointAdmNoSet struct {
	NumberOfCharacters byte

	MeterPointAdmNumberCharacter []byte
}

func ParseMeterTblTablePointAdmNoSet(payload []byte) MeterTblTablePointAdmNoSet {
	val := MeterTblTablePointAdmNoSet{}

	i := 2

	val.NumberOfCharacters = (payload[i] & 0x1F)

	i += 1

	val.MeterPointAdmNumberCharacter = payload[i : i+0]
	i += 0

	return val
}
