// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package securitypanelmode

import (
	"encoding/gob"
	"errors"
)

func init() {
	gob.Register(SecurityPanelModeSet{})
}

// <no value>
type SecurityPanelModeSet struct {
	Mode byte
}

func (cmd *SecurityPanelModeSet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Mode = payload[i]
	i++

	return nil
}

func (cmd *SecurityPanelModeSet) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.Mode)

	return
}
