// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package securitypanelmode

import (
	"encoding/binary"
	"errors"
)

// <no value>

type SecurityPanelModeSupportedReport struct {
	SupportedModeBitMask uint16
}

func (cmd *SecurityPanelModeSupportedReport) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SupportedModeBitMask = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	return nil
}
