// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package securitypanelmode

// <no value>

type SecurityPanelModeSupportedGet struct {
}

func (cmd *SecurityPanelModeSupportedGet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *SecurityPanelModeSupportedGet) MarshalBinary() (payload []byte, err error) {

	return
}
