// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package scheduleentrylockv3

// <no value>

type ScheduleEntryLockDailyRepeatingSet struct {
	SetAction byte

	UserIdentifier byte

	ScheduleSlotId byte

	WeekDayBitmask byte

	StartHour byte

	StartMinute byte

	DurationHour byte

	DurationMinute byte
}

func ParseScheduleEntryLockDailyRepeatingSet(payload []byte) ScheduleEntryLockDailyRepeatingSet {
	val := ScheduleEntryLockDailyRepeatingSet{}

	i := 2

	val.SetAction = payload[i]
	i++

	val.UserIdentifier = payload[i]
	i++

	val.ScheduleSlotId = payload[i]
	i++

	val.WeekDayBitmask = payload[i]
	i++

	val.StartHour = payload[i]
	i++

	val.StartMinute = payload[i]
	i++

	val.DurationHour = payload[i]
	i++

	val.DurationMinute = payload[i]
	i++

	return val
}
