// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package dmx

// <no value>

type DmxAddressSet struct {
	Properties1 struct {
		PageId byte
	}

	ChannelId byte
}

func ParseDmxAddressSet(payload []byte) DmxAddressSet {
	val := DmxAddressSet{}

	i := 2

	val.Properties1.PageId = (payload[i] & 0x0F)

	i += 1

	val.ChannelId = payload[i]
	i++

	return val
}
