// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package dmx

// <no value>

type DmxAddressGet struct {
}

func ParseDmxAddressGet(payload []byte) DmxAddressGet {
	val := DmxAddressGet{}

	return val
}
