// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package colorcontrolv2

import (
	"encoding/binary"
	"errors"
)

// <no value>

type CapabilityReport struct {
	CapabilityMask uint16
}

func (cmd *CapabilityReport) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.CapabilityMask = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	return nil
}
