// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package colorcontrolv2

// <no value>

type CapabilityGet struct {
}

func ParseCapabilityGet(payload []byte) CapabilityGet {
	val := CapabilityGet{}

	return val
}
