// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package colorcontrolv2

import (
	"encoding/gob"
	"errors"
)

func init() {
	gob.Register(StateReport{})
}

// <no value>
type StateReport struct {
	CapabilityId byte

	State byte
}

func (cmd *StateReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.CapabilityId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.State = payload[i]
	i++

	return nil
}

func (cmd *StateReport) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.CapabilityId)

	payload = append(payload, cmd.State)

	return
}
