// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package associationcommandconfiguration

// <no value>

type CommandConfigurationReport struct {
	GroupingIdentifier byte

	NodeId byte

	ReportsToFollow byte

	First bool

	CommandLength byte

	CommandClassIdentifier byte

	CommandIdentifier byte

	CommandByte []byte
}

func ParseCommandConfigurationReport(payload []byte) CommandConfigurationReport {
	val := CommandConfigurationReport{}

	i := 2

	val.GroupingIdentifier = payload[i]
	i++

	val.NodeId = payload[i]
	i++

	val.ReportsToFollow = (payload[i] & 0x0F)

	if payload[i]&0x80 == 0x80 {
		val.First = true
	} else {
		val.First = false
	}

	i += 1

	val.CommandLength = payload[i]
	i++

	val.CommandClassIdentifier = payload[i]
	i++

	val.CommandIdentifier = payload[i]
	i++

	val.CommandByte = payload[i:]

	return val
}
