// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package associationcommandconfiguration

import "encoding/gob"

func init() {
	gob.Register(CommandRecordsSupportedGet{})
}

// <no value>
type CommandRecordsSupportedGet struct {
}

func (cmd *CommandRecordsSupportedGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)

	return nil
}

func (cmd *CommandRecordsSupportedGet) MarshalBinary() (payload []byte, err error) {

	return
}
