// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package associationcommandconfiguration

import "encoding/binary"

// <no value>

type CommandRecordsSupportedReport struct {
	MaxCommandLength byte

	ConfCmd bool

	Vc bool

	FreeCommandRecords uint16

	MaxCommandRecords uint16
}

func ParseCommandRecordsSupportedReport(payload []byte) CommandRecordsSupportedReport {
	val := CommandRecordsSupportedReport{}

	i := 2

	val.MaxCommandLength = (payload[i] & 0xFC) << 2

	if payload[i]&0x01 == 0x01 {
		val.ConfCmd = true
	} else {
		val.ConfCmd = false
	}

	if payload[i]&0x02 == 0x02 {
		val.Vc = true
	} else {
		val.Vc = false
	}

	i += 1

	val.FreeCommandRecords = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	val.MaxCommandRecords = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	return val
}
