// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package version

import "errors"

// <no value>

type VersionReport struct {
	ZWaveLibraryType byte

	ZWaveProtocolVersion byte

	ZWaveProtocolSubVersion byte

	ApplicationVersion byte

	ApplicationSubVersion byte
}

func (cmd *VersionReport) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ZWaveLibraryType = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ZWaveProtocolVersion = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ZWaveProtocolSubVersion = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ApplicationVersion = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ApplicationSubVersion = payload[i]
	i++

	return nil
}

func (cmd *VersionReport) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.ZWaveLibraryType)

	payload = append(payload, cmd.ZWaveProtocolVersion)

	payload = append(payload, cmd.ZWaveProtocolSubVersion)

	payload = append(payload, cmd.ApplicationVersion)

	payload = append(payload, cmd.ApplicationSubVersion)

	return
}
