// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package avcontentsearchmd

// <no value>

type AvContentSearchMdGet struct {
}

func (cmd *AvContentSearchMdGet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *AvContentSearchMdGet) MarshalBinary() (payload []byte, err error) {

	return
}
