// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package avcontentsearchmd

// <no value>

type AvContentSearchMdReport struct {
}

func (cmd *AvContentSearchMdReport) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *AvContentSearchMdReport) MarshalBinary() (payload []byte, err error) {

	return
}
