// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package avcontentsearchmd

import "encoding/gob"

func init() {
	gob.Register(AvContentSearchMdReport{})
}

// <no value>
type AvContentSearchMdReport struct {
}

func (cmd *AvContentSearchMdReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)

	return nil
}

func (cmd *AvContentSearchMdReport) MarshalBinary() (payload []byte, err error) {

	return
}
