// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package dcpconfig

// <no value>

type DcpListSupportedGet struct {
}

func ParseDcpListSupportedGet(payload []byte) DcpListSupportedGet {
	val := DcpListSupportedGet{}

	return val
}
