// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package sensormultilevelv5

// <no value>

type SensorMultilevelSupportedGetSensor struct {
}

func (cmd *SensorMultilevelSupportedGetSensor) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *SensorMultilevelSupportedGetSensor) MarshalBinary() (payload []byte, err error) {

	return
}
