// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package sensormultilevelv5

import "encoding/gob"

func init() {
	gob.Register(SensorMultilevelSupportedGetSensor{})
}

// <no value>
type SensorMultilevelSupportedGetSensor struct {
}

func (cmd *SensorMultilevelSupportedGetSensor) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)

	return nil
}

func (cmd *SensorMultilevelSupportedGetSensor) MarshalBinary() (payload []byte, err error) {

	return
}
