// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package sensormultilevelv5

// <no value>

type SensorMultilevelSupportedSensorReport struct {
	BitMask byte
}

func ParseSensorMultilevelSupportedSensorReport(payload []byte) SensorMultilevelSupportedSensorReport {
	val := SensorMultilevelSupportedSensorReport{}

	i := 2

	val.BitMask = payload[i]
	i++

	return val
}
