// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package zwaveplusinfov2

import "encoding/gob"

func init() {
	gob.Register(ZwaveplusInfoGet{})
}

// <no value>
type ZwaveplusInfoGet struct {
}

func (cmd *ZwaveplusInfoGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)

	return nil
}

func (cmd *ZwaveplusInfoGet) MarshalBinary() (payload []byte, err error) {

	return
}
