// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package avcontentdirectorymd

// <no value>

type AvContentBrowseMdByLetterGet struct {
}

func (cmd *AvContentBrowseMdByLetterGet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *AvContentBrowseMdByLetterGet) MarshalBinary() (payload []byte, err error) {

	return
}
