// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package avcontentdirectorymd

// <no value>

type AvContentBrowseMdGet struct {
}

func ParseAvContentBrowseMdGet(payload []byte) AvContentBrowseMdGet {
	val := AvContentBrowseMdGet{}

	return val
}
