// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package avcontentdirectorymd

// <no value>

type AvContentBrowseMdReport struct {
}

func (cmd *AvContentBrowseMdReport) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *AvContentBrowseMdReport) MarshalBinary() (payload []byte, err error) {

	return
}
