// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package avcontentdirectorymd

// <no value>

type AvContentBrowseMdByLetterGet struct {
}

func ParseAvContentBrowseMdByLetterGet(payload []byte) AvContentBrowseMdByLetterGet {
	val := AvContentBrowseMdByLetterGet{}

	return val
}
