// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package avcontentdirectorymd

// <no value>

type AvContentBrowseMdGet struct {
}

func (cmd *AvContentBrowseMdGet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *AvContentBrowseMdGet) MarshalBinary() (payload []byte, err error) {

	return
}
