// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package avcontentdirectorymd

// <no value>

type AvContentBrowseMdByLetterReport struct {
}

func ParseAvContentBrowseMdByLetterReport(payload []byte) AvContentBrowseMdByLetterReport {
	val := AvContentBrowseMdByLetterReport{}

	return val
}
