// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package security

import (
	"encoding/gob"
	"errors"

	"github.com/gozwave/gozw/cc"
)

const CommandSchemeReport cc.CommandID = 0x05

func init() {
	gob.Register(SchemeReport{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x98),
		Command:      cc.CommandID(0x05),
		Version:      1,
	}, NewSchemeReport)
}

func NewSchemeReport() cc.Command {
	return &SchemeReport{}
}

// <no value>
type SchemeReport struct {
	SupportedSecuritySchemes byte
}

func (cmd SchemeReport) CommandClassID() cc.CommandClassID {
	return 0x98
}

func (cmd SchemeReport) CommandID() cc.CommandID {
	return CommandSchemeReport
}

func (cmd SchemeReport) CommandIDString() string {
	return "SECURITY_SCHEME_REPORT"
}

func (cmd *SchemeReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SupportedSecuritySchemes = payload[i]
	i++

	return nil
}

func (cmd *SchemeReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.SupportedSecuritySchemes)

	return
}
