// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package sensorconfiguration

// <no value>

type SensorTriggerLevelSet struct {
	Current bool

	Default bool

	SensorType byte

	Size byte

	Scale byte

	Precision byte

	TriggerValue []byte
}

func ParseSensorTriggerLevelSet(payload []byte) SensorTriggerLevelSet {
	val := SensorTriggerLevelSet{}

	i := 2

	if payload[i]&0x40 == 0x40 {
		val.Current = true
	} else {
		val.Current = false
	}

	if payload[i]&0x80 == 0x80 {
		val.Default = true
	} else {
		val.Default = false
	}

	i += 1

	val.SensorType = payload[i]
	i++

	val.Size = (payload[i] & 0x07)

	val.Scale = (payload[i] & 0x18) << 3

	val.Precision = (payload[i] & 0xE0) << 5

	i += 1

	val.TriggerValue = payload[i : i+2]
	i += 2

	return val
}
