// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package sensorconfiguration

import (
	"encoding/gob"
	"errors"
)

func init() {
	gob.Register(SensorTriggerLevelReport{})
}

// <no value>
type SensorTriggerLevelReport struct {
	SensorType byte

	Properties1 struct {
		Size byte

		Scale byte

		Precision byte
	}

	TriggerValue []byte
}

func (cmd *SensorTriggerLevelReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SensorType = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.Size = (payload[i] & 0x07)

	cmd.Properties1.Scale = (payload[i] & 0x18) >> 3

	cmd.Properties1.Precision = (payload[i] & 0xE0) >> 5

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.TriggerValue = payload[i : i+1]
	i += 1

	return nil
}

func (cmd *SensorTriggerLevelReport) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.SensorType)

	{
		var val byte

		val |= (cmd.Properties1.Size) & byte(0x07)

		val |= (cmd.Properties1.Scale << byte(3)) & byte(0x18)

		val |= (cmd.Properties1.Precision << byte(5)) & byte(0xE0)

		payload = append(payload, val)
	}

	if cmd.TriggerValue != nil && len(cmd.TriggerValue) > 0 {
		payload = append(payload, cmd.TriggerValue...)
	}

	return
}
