// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package multiinstanceassociation

// <no value>

type MultiInstanceAssociationGet struct {
	GroupingIdentifier byte
}

func ParseMultiInstanceAssociationGet(payload []byte) MultiInstanceAssociationGet {
	val := MultiInstanceAssociationGet{}

	i := 2

	val.GroupingIdentifier = payload[i]
	i++

	return val
}
