// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package multiinstanceassociation

// <no value>

type MultiInstanceAssociationGroupingsReport struct {
	SupportedGroupings byte
}

func ParseMultiInstanceAssociationGroupingsReport(payload []byte) MultiInstanceAssociationGroupingsReport {
	val := MultiInstanceAssociationGroupingsReport{}

	i := 2

	val.SupportedGroupings = payload[i]
	i++

	return val
}
