// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package multiinstanceassociation

// <no value>

type MultiInstanceAssociationGroupingsGet struct {
}

func (cmd *MultiInstanceAssociationGroupingsGet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *MultiInstanceAssociationGroupingsGet) MarshalBinary() (payload []byte, err error) {

	return
}
