// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package associationgrpinfo

// <no value>

type AssociationGroupCommandListGet struct {
	Properties1 struct {
		AllowCache bool
	}

	GroupingIdentifier byte
}

func ParseAssociationGroupCommandListGet(payload []byte) AssociationGroupCommandListGet {
	val := AssociationGroupCommandListGet{}

	i := 2

	if payload[i]&0x80 == 0x80 {
		val.Properties1.AllowCache = true
	} else {
		val.Properties1.AllowCache = false
	}

	i += 1

	val.GroupingIdentifier = payload[i]
	i++

	return val
}
