// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package associationgrpinfo

// <no value>

type AssociationGroupNameGet struct {
	GroupingIdentifier byte
}

func ParseAssociationGroupNameGet(payload []byte) AssociationGroupNameGet {
	val := AssociationGroupNameGet{}

	i := 2

	val.GroupingIdentifier = payload[i]
	i++

	return val
}
