// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package thermostatoperatingstatev2

import (
	"encoding/gob"
	"errors"

	"github.com/helioslabs/gozw/command-class"
)

const CommandLoggingReport commandclass.CommandID = 0x06

func init() {
	gob.Register(LoggingReport{})
	commandclass.Register(commandclass.CommandIdentifier{
		CommandClass: commandclass.CommandClassID(0x42),
		Command:      commandclass.CommandID(0x06),
		Version:      2,
	}, NewLoggingReport)
}

func NewLoggingReport() commandclass.Command {
	return &LoggingReport{}
}

// <no value>
type LoggingReport struct {
	ReportsToFollow byte
}

func (cmd LoggingReport) CommandClassID() commandclass.CommandClassID {
	return 0x42
}

func (cmd LoggingReport) CommandID() commandclass.CommandID {
	return CommandLoggingReport
}

func (cmd LoggingReport) CommandIDString() string {
	return "THERMOSTAT_OPERATING_STATE_LOGGING_REPORT"
}

func (cmd *LoggingReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ReportsToFollow = payload[i]
	i++

	return nil
}

func (cmd *LoggingReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	payload = append(payload, cmd.ReportsToFollow)

	return
}
