// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchmultilevelv2

// <no value>

type SwitchMultilevelGet struct {
}

func ParseSwitchMultilevelGet(payload []byte) SwitchMultilevelGet {
	val := SwitchMultilevelGet{}

	return val
}
