// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchmultilevelv2

// <no value>

type SwitchMultilevelSet struct {
	Value byte

	DimmingDuration byte
}

func ParseSwitchMultilevelSet(payload []byte) SwitchMultilevelSet {
	val := SwitchMultilevelSet{}

	i := 2

	val.Value = payload[i]
	i++

	val.DimmingDuration = payload[i]
	i++

	return val
}
