// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchmultilevelv2

// <no value>

type SwitchMultilevelStopLevelChange struct {
}

func (cmd *SwitchMultilevelStopLevelChange) UnmarshalBinary(payload []byte) error {

	return nil
}
