// THIS FILE IS AUTO-GENERATED BY ZWGEN
// DO NOT MODIFY

package meterv3

import (
	"encoding/gob"

	"github.com/gozwave/gozw/cc"
)

const CommandReset cc.CommandID = 0x05

func init() {
	gob.Register(Reset{})
	cc.Register(cc.CommandIdentifier{
		CommandClass: cc.CommandClassID(0x32),
		Command:      cc.CommandID(0x05),
		Version:      3,
	}, NewReset)
}

func NewReset() cc.Command {
	return &Reset{}
}

// <no value>
type Reset struct {
}

func (cmd Reset) CommandClassID() cc.CommandClassID {
	return 0x32
}

func (cmd Reset) CommandID() cc.CommandID {
	return CommandReset
}

func (cmd Reset) CommandIDString() string {
	return "METER_RESET"
}

func (cmd *Reset) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *Reset) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
