// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package sensormultilevelv2

// <no value>

type SensorMultilevelGet struct {
}

func ParseSensorMultilevelGet(payload []byte) SensorMultilevelGet {
	val := SensorMultilevelGet{}

	return val
}
