// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package notificationv4

// <no value>

type NotificationSet struct {
	NotificationType byte

	NotificationStatus byte
}

func ParseNotificationSet(payload []byte) NotificationSet {
	val := NotificationSet{}

	i := 2

	val.NotificationType = payload[i]
	i++

	val.NotificationStatus = payload[i]
	i++

	return val
}
