// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package multichannelv2

import (
	"encoding/gob"
	"errors"
)

func init() {
	gob.Register(MultiChannelCapabilityGet{})
}

// <no value>
type MultiChannelCapabilityGet struct {
	Properties1 struct {
		EndPoint byte
	}
}

func (cmd *MultiChannelCapabilityGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.EndPoint = (payload[i] & 0x7F)

	i += 1

	return nil
}

func (cmd *MultiChannelCapabilityGet) MarshalBinary() (payload []byte, err error) {

	{
		var val byte

		val |= (cmd.Properties1.EndPoint) & byte(0x7F)

		payload = append(payload, val)
	}

	return
}
