// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package multichannelv2

// <no value>

type MultiChannelEndPointGet struct {
}

func ParseMultiChannelEndPointGet(payload []byte) MultiChannelEndPointGet {
	val := MultiChannelEndPointGet{}

	return val
}
