// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchtogglemultilevel

// <no value>

type SwitchToggleMultilevelGet struct {
}

func ParseSwitchToggleMultilevelGet(payload []byte) SwitchToggleMultilevelGet {
	val := SwitchToggleMultilevelGet{}

	return val
}
