// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchtogglemultilevel

import "errors"

// <no value>

type SwitchToggleMultilevelReport struct {
	Value byte
}

func (cmd *SwitchToggleMultilevelReport) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Value = payload[i]
	i++

	return nil
}
