// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchtogglemultilevel

// <no value>

type SwitchToggleMultilevelSet struct {
}

func (cmd *SwitchToggleMultilevelSet) UnmarshalBinary(payload []byte) error {

	return nil
}
