// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchtogglemultilevel

// <no value>

type SwitchToggleMultilevelStartLevelChange struct {
	Level struct {
		IgnoreStartLevel bool

		RollOver bool
	}

	StartLevel byte
}

func ParseSwitchToggleMultilevelStartLevelChange(payload []byte) SwitchToggleMultilevelStartLevelChange {
	val := SwitchToggleMultilevelStartLevelChange{}

	i := 2

	if payload[i]&0x20 == 0x20 {
		val.Level.IgnoreStartLevel = true
	} else {
		val.Level.IgnoreStartLevel = false
	}

	if payload[i]&0x80 == 0x80 {
		val.Level.RollOver = true
	} else {
		val.Level.RollOver = false
	}

	i += 1

	val.StartLevel = payload[i]
	i++

	return val
}
