// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchtogglemultilevel

import "encoding/gob"

func init() {
	gob.Register(SwitchToggleMultilevelStopLevelChange{})
}

// <no value>
type SwitchToggleMultilevelStopLevelChange struct {
}

func (cmd *SwitchToggleMultilevelStopLevelChange) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)

	return nil
}

func (cmd *SwitchToggleMultilevelStopLevelChange) MarshalBinary() (payload []byte, err error) {

	return
}
