// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package avrendererstatus

import "encoding/gob"

func init() {
	gob.Register(AvRendererStatusGet{})
}

// <no value>
type AvRendererStatusGet struct {
}

func (cmd *AvRendererStatusGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)

	return nil
}

func (cmd *AvRendererStatusGet) MarshalBinary() (payload []byte, err error) {

	return
}
