// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package avrendererstatus

// <no value>

type AvRendererStatusReport struct {
}

func ParseAvRendererStatusReport(payload []byte) AvRendererStatusReport {
	val := AvRendererStatusReport{}

	return val
}
