// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package associationv2

import (
	"encoding/gob"
	"errors"
)

func init() {
	gob.Register(GroupingsReport{})
}

// <no value>
type GroupingsReport struct {
	SupportedGroupings byte
}

func (cmd GroupingsReport) CommandClassID() byte {
	return 0x85
}

func (cmd GroupingsReport) CommandID() byte {
	return byte(CommandGroupingsReport)
}

func (cmd *GroupingsReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SupportedGroupings = payload[i]
	i++

	return nil
}

func (cmd *GroupingsReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = cmd.CommandClassID()
	payload[1] = cmd.CommandID()

	payload = append(payload, cmd.SupportedGroupings)

	return
}
