// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package associationv2

// <no value>

type AssociationSpecificGroupGet struct {
}

func (cmd *AssociationSpecificGroupGet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *AssociationSpecificGroupGet) MarshalBinary() (payload []byte, err error) {

	return
}
