// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package associationv2

import (
	"encoding/gob"
	"errors"
)

func init() {
	gob.Register(AssociationSpecificGroupReport{})
}

// <no value>
type AssociationSpecificGroupReport struct {
	Group byte
}

func (cmd *AssociationSpecificGroupReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Group = payload[i]
	i++

	return nil
}

func (cmd *AssociationSpecificGroupReport) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.Group)

	return
}
