// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package hrvstatus

// <no value>

type HrvStatusGet struct {
	StatusParameter byte
}

func ParseHrvStatusGet(payload []byte) HrvStatusGet {
	val := HrvStatusGet{}

	i := 2

	val.StatusParameter = payload[i]
	i++

	return val
}
