// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package securitypanelzonesensor

import "errors"

// <no value>

type CommandClassSecurityPanelZoneSensorInstalledReport struct {
	ZoneNumber byte

	NumberOfSensors byte
}

func (cmd *CommandClassSecurityPanelZoneSensorInstalledReport) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ZoneNumber = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NumberOfSensors = payload[i]
	i++

	return nil
}
