// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package securitypanelzonesensor

import "errors"

// <no value>

type SecurityPanelZoneSensorStateGet struct {
	ZoneNumber byte

	SensorNumber byte
}

func (cmd *SecurityPanelZoneSensorStateGet) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ZoneNumber = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SensorNumber = payload[i]
	i++

	return nil
}

func (cmd *SecurityPanelZoneSensorStateGet) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.ZoneNumber)

	payload = append(payload, cmd.SensorNumber)

	return
}
