// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package securitypanelzonesensor

import (
	"encoding/gob"
	"errors"
)

func init() {
	gob.Register(SecurityPanelZoneSensorTypeGet{})
}

// <no value>
type SecurityPanelZoneSensorTypeGet struct {
	ZoneNumber byte

	SensorNumber byte
}

func (cmd *SecurityPanelZoneSensorTypeGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ZoneNumber = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SensorNumber = payload[i]
	i++

	return nil
}

func (cmd *SecurityPanelZoneSensorTypeGet) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.ZoneNumber)

	payload = append(payload, cmd.SensorNumber)

	return
}
