// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package thermostatfanmodev2

import (
	"encoding/gob"
	"errors"
)

func init() {
	gob.Register(ThermostatFanModeSet{})
}

// <no value>
type ThermostatFanModeSet struct {
	Level struct {
		Off bool

		FanMode byte
	}
}

func (cmd *ThermostatFanModeSet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Level.FanMode = (payload[i] & 0x0F)

	if payload[i]&0x80 == 0x80 {
		cmd.Level.Off = true
	} else {
		cmd.Level.Off = false
	}

	i += 1

	return nil
}

func (cmd *ThermostatFanModeSet) MarshalBinary() (payload []byte, err error) {

	{
		var val byte

		val |= (cmd.Level.FanMode) & byte(0x0F)

		if cmd.Level.Off {
			val |= byte(0x80) // flip bits on
		} else {
			val &= ^byte(0x80) // flip bits off
		}

		payload = append(payload, val)
	}

	return
}
