// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package thermostatoperatingstate

// <no value>

type ThermostatOperatingStateGet struct {
}

func (cmd *ThermostatOperatingStateGet) UnmarshalBinary(payload []byte) error {

	return nil
}
