// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package manufacturerspecificv2

// <no value>

type DeviceSpecificReport struct {
	Properties1 struct {
		DeviceIdType byte
	}

	Properties2 struct {
		DeviceIdDataLengthIndicator byte

		DeviceIdDataFormat byte
	}

	DeviceIdData []byte
}

func ParseDeviceSpecificReport(payload []byte) DeviceSpecificReport {
	val := DeviceSpecificReport{}

	i := 2

	val.Properties1.DeviceIdType = (payload[i] & 0x07)

	i += 1

	val.Properties2.DeviceIdDataLengthIndicator = (payload[i] & 0x1F)

	val.Properties2.DeviceIdDataFormat = (payload[i] & 0xE0) << 5

	i += 1

	val.DeviceIdData = payload[i:]

	return val
}
