// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package manufacturerspecificv2

// <no value>

type DeviceSpecificReport struct {
	DeviceIdType byte

	DeviceIdDataLengthIndicator byte

	DeviceIdDataFormat byte

	DeviceIdData []byte
}

func ParseDeviceSpecificReport(payload []byte) DeviceSpecificReport {
	val := DeviceSpecificReport{}

	i := 2

	val.DeviceIdType = (payload[i] & 0x07)

	i += 1

	val.DeviceIdDataLengthIndicator = (payload[i] & 0x1F)

	val.DeviceIdDataFormat = (payload[i] & 0xE0) << 5

	i += 1

	val.DeviceIdData = payload[i:]

	return val
}
