// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package manufacturerspecificv2

import (
	"encoding/gob"
	"errors"
)

func init() {
	gob.Register(DeviceSpecificGet{})
}

// <no value>
type DeviceSpecificGet struct {
	Properties1 struct {
		DeviceIdType byte
	}
}

func (cmd DeviceSpecificGet) CommandClassID() byte {
	return 0x72
}

func (cmd DeviceSpecificGet) CommandID() byte {
	return byte(CommandDeviceSpecificGet)
}

func (cmd *DeviceSpecificGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.DeviceIdType = (payload[i] & 0x07)

	i += 1

	return nil
}

func (cmd *DeviceSpecificGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = cmd.CommandClassID()
	payload[1] = cmd.CommandID()

	{
		var val byte

		val |= (cmd.Properties1.DeviceIdType) & byte(0x07)

		payload = append(payload, val)
	}

	return
}
