// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package metertblmonitorv2

// <no value>

type MeterTblStatusSupportedGet struct {
}

func ParseMeterTblStatusSupportedGet(payload []byte) MeterTblStatusSupportedGet {
	val := MeterTblStatusSupportedGet{}

	return val
}
