// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package metertblmonitorv2

// <no value>

type MeterTblTablePointAdmNoGet struct {
}

func (cmd *MeterTblTablePointAdmNoGet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *MeterTblTablePointAdmNoGet) MarshalBinary() (payload []byte, err error) {

	return
}
