// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package metertblmonitorv2

// <no value>

type MeterTblTableIdGet struct {
}

func (cmd *MeterTblTableIdGet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *MeterTblTableIdGet) MarshalBinary() (payload []byte, err error) {

	return
}
