// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package metertblmonitorv2

import "encoding/binary"

// <no value>

type MeterTblReport struct {
	Properties1 struct {
		MeterType byte

		RateType byte
	}

	Properties2 struct {
		PayMeter byte
	}

	DatasetSupported uint32

	DatasetHistorySupported uint32

	DataHistorySupported uint32
}

func ParseMeterTblReport(payload []byte) MeterTblReport {
	val := MeterTblReport{}

	i := 2

	val.Properties1.MeterType = (payload[i] & 0x3F)

	val.Properties1.RateType = (payload[i] & 0xC0) << 6

	i += 1

	val.Properties2.PayMeter = (payload[i] & 0x0F)

	i += 1

	val.DatasetSupported = binary.BigEndian.Uint32(payload[i : i+3])
	i += 3

	val.DatasetHistorySupported = binary.BigEndian.Uint32(payload[i : i+3])
	i += 3

	val.DataHistorySupported = binary.BigEndian.Uint32(payload[i : i+3])
	i += 3

	return val
}
