// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package meterpulse

import "encoding/gob"

func init() {
	gob.Register(MeterPulseGet{})
}

// <no value>
type MeterPulseGet struct {
}

func (cmd *MeterPulseGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)

	return nil
}

func (cmd *MeterPulseGet) MarshalBinary() (payload []byte, err error) {

	return
}
