// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchbinary

// <no value>

type SwitchBinaryGet struct {
}

func (cmd *SwitchBinaryGet) UnmarshalBinary(payload []byte) error {

	return nil
}
