// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchbinary

import "errors"

// <no value>

type SwitchBinaryReport struct {
	Value byte
}

func (cmd *SwitchBinaryReport) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Value = payload[i]
	i++

	return nil
}
