// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchbinary

// <no value>

type SwitchBinarySet struct {
	SwitchValue byte
}

func ParseSwitchBinarySet(payload []byte) SwitchBinarySet {
	val := SwitchBinarySet{}

	i := 2

	val.SwitchValue = payload[i]
	i++

	return val
}
