// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package chimneyfan

// <no value>

type ChimneyFanAlarmLogGet struct {
}

func (cmd *ChimneyFanAlarmLogGet) UnmarshalBinary(payload []byte) error {

	return nil
}
