// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package chimneyfan

import "errors"

// <no value>

type ChimneyFanAlarmLogSet struct {
	Message byte
}

func (cmd *ChimneyFanAlarmLogSet) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Message = payload[i]
	i++

	return nil
}

func (cmd *ChimneyFanAlarmLogSet) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.Message)

	return
}
