// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package chimneyfan

// <no value>

type ChimneyFanBoostTimeGet struct {
}

func (cmd *ChimneyFanBoostTimeGet) UnmarshalBinary(payload []byte) error {

	return nil
}
