// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package chimneyfan

// <no value>

type ChimneyFanDefaultSet struct {
}

func (cmd *ChimneyFanDefaultSet) UnmarshalBinary(payload []byte) error {

	return nil
}
