// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package chimneyfan

// <no value>

type ChimneyFanDefaultSet struct {
}

func ParseChimneyFanDefaultSet(payload []byte) ChimneyFanDefaultSet {
	val := ChimneyFanDefaultSet{}

	return val
}
