// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package chimneyfan

// <no value>

type ChimneyFanMinSpeedGet struct {
}

func (cmd *ChimneyFanMinSpeedGet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *ChimneyFanMinSpeedGet) MarshalBinary() (payload []byte, err error) {

	return
}
