// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package chimneyfan

// <no value>

type ChimneyFanModeReport struct {
	Mode byte
}

func ParseChimneyFanModeReport(payload []byte) ChimneyFanModeReport {
	val := ChimneyFanModeReport{}

	i := 2

	val.Mode = payload[i]
	i++

	return val
}
