// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package chimneyfan

// <no value>

type ChimneyFanModeGet struct {
}

func (cmd *ChimneyFanModeGet) UnmarshalBinary(payload []byte) error {

	return nil
}
