// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package chimneyfan

import "encoding/gob"

func init() {
	gob.Register(ChimneyFanModeGet{})
}

// <no value>
type ChimneyFanModeGet struct {
}

func (cmd *ChimneyFanModeGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)

	return nil
}

func (cmd *ChimneyFanModeGet) MarshalBinary() (payload []byte, err error) {

	return
}
