// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package chimneyfan

// <no value>

type ChimneyFanSpeedReport struct {
	Speed byte
}

func ParseChimneyFanSpeedReport(payload []byte) ChimneyFanSpeedReport {
	val := ChimneyFanSpeedReport{}

	i := 2

	val.Speed = payload[i]
	i++

	return val
}
