// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package chimneyfan

// <no value>

type ChimneyFanStartTempSet struct {
	Size byte

	Scale byte

	Precision byte

	Value []byte
}

func ParseChimneyFanStartTempSet(payload []byte) ChimneyFanStartTempSet {
	val := ChimneyFanStartTempSet{}

	i := 2

	val.Size = (payload[i] & 0x07)

	val.Scale = (payload[i] & 0x18) << 3

	val.Precision = (payload[i] & 0xE0) << 5

	i += 1

	val.Value = payload[i : i+0]
	i += 0

	return val
}
