// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package chimneyfan

// <no value>

type ChimneyFanStartTempGet struct {
}

func (cmd *ChimneyFanStartTempGet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *ChimneyFanStartTempGet) MarshalBinary() (payload []byte, err error) {

	return
}
