// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package chimneyfan

// <no value>

type ChimneyFanStateGet struct {
}

func (cmd *ChimneyFanStateGet) UnmarshalBinary(payload []byte) error {

	return nil
}
