// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package chimneyfan

// <no value>

type ChimneyFanStateReport struct {
	State byte
}

func ParseChimneyFanStateReport(payload []byte) ChimneyFanStateReport {
	val := ChimneyFanStateReport{}

	i := 2

	val.State = payload[i]
	i++

	return val
}
