// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package chimneyfan

// <no value>

type ChimneyFanStateGet struct {
}

func ParseChimneyFanStateGet(payload []byte) ChimneyFanStateGet {
	val := ChimneyFanStateGet{}

	return val
}
