// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package chimneyfan

// <no value>

type ChimneyFanStatusGet struct {
}

func (cmd *ChimneyFanStatusGet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *ChimneyFanStatusGet) MarshalBinary() (payload []byte, err error) {

	return
}
