// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package chimneyfan

// <no value>

type ChimneyFanStopTimeGet struct {
}

func ParseChimneyFanStopTimeGet(payload []byte) ChimneyFanStopTimeGet {
	val := ChimneyFanStopTimeGet{}

	return val
}
