// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package chimneyfan

// <no value>

type ChimneyFanStopTimeGet struct {
}

func (cmd *ChimneyFanStopTimeGet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *ChimneyFanStopTimeGet) MarshalBinary() (payload []byte, err error) {

	return
}
