// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package protectionv2

// <no value>

type ProtectionEcGet struct {
}

func (cmd *ProtectionEcGet) UnmarshalBinary(payload []byte) error {

	return nil
}
