// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package protectionv2

// <no value>

type ProtectionEcReport struct {
	NodeId byte
}

func ParseProtectionEcReport(payload []byte) ProtectionEcReport {
	val := ProtectionEcReport{}

	i := 2

	val.NodeId = payload[i]
	i++

	return val
}
