// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package protectionv2

import "errors"

// <no value>

type ProtectionSet struct {
	Level struct {
		LocalProtectionState byte
	}

	Level2 struct {
		RfProtectionState byte
	}
}

func (cmd *ProtectionSet) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Level.LocalProtectionState = (payload[i] & 0x0F)

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Level2.RfProtectionState = (payload[i] & 0x0F)

	i += 1

	return nil
}

func (cmd *ProtectionSet) MarshalBinary() (payload []byte, err error) {

	{
		var val byte

		val |= (cmd.Level.LocalProtectionState) & byte(0x0F)

		payload = append(payload, val)
	}

	{
		var val byte

		val |= (cmd.Level2.RfProtectionState) & byte(0x0F)

		payload = append(payload, val)
	}

	return
}
