// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package protectionv2

// <no value>

type ProtectionTimeoutReport struct {
	Timeout byte
}

func ParseProtectionTimeoutReport(payload []byte) ProtectionTimeoutReport {
	val := ProtectionTimeoutReport{}

	i := 2

	val.Timeout = payload[i]
	i++

	return val
}
