// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package protectionv2

import "encoding/gob"

func init() {
	gob.Register(ProtectionTimeoutGet{})
}

// <no value>
type ProtectionTimeoutGet struct {
}

func (cmd *ProtectionTimeoutGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)

	return nil
}

func (cmd *ProtectionTimeoutGet) MarshalBinary() (payload []byte, err error) {

	return
}
