// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package protection

import "errors"

// <no value>

type ProtectionReport struct {
	ProtectionState byte
}

func (cmd *ProtectionReport) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ProtectionState = payload[i]
	i++

	return nil
}
