// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package protection

// <no value>

type ProtectionSet struct {
	ProtectionState byte
}

func ParseProtectionSet(payload []byte) ProtectionSet {
	val := ProtectionSet{}

	i := 2

	val.ProtectionState = payload[i]
	i++

	return val
}
