// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package sceneactuatorconf

import "errors"

// <no value>

type SceneActuatorConfReport struct {
	SceneId byte

	Level byte

	DimmingDuration byte
}

func (cmd *SceneActuatorConfReport) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SceneId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Level = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.DimmingDuration = payload[i]
	i++

	return nil
}

func (cmd *SceneActuatorConfReport) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.SceneId)

	payload = append(payload, cmd.Level)

	payload = append(payload, cmd.DimmingDuration)

	return
}
