// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package climatecontrolschedule

// <no value>

type ScheduleChangedGet struct {
}

func ParseScheduleChangedGet(payload []byte) ScheduleChangedGet {
	val := ScheduleChangedGet{}

	return val
}
