// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package climatecontrolschedule

import "encoding/binary"

// <no value>

type ScheduleReport struct {
	Weekday byte

	Switchpoint0 uint32

	Switchpoint1 uint32

	Switchpoint2 uint32

	Switchpoint3 uint32

	Switchpoint4 uint32

	Switchpoint5 uint32

	Switchpoint6 uint32

	Switchpoint7 uint32

	Switchpoint8 uint32
}

func ParseScheduleReport(payload []byte) ScheduleReport {
	val := ScheduleReport{}

	i := 2

	val.Weekday = (payload[i] & 0x07)

	i += 1

	val.Switchpoint0 = binary.BigEndian.Uint32(payload[i : i+3])
	i += 3

	val.Switchpoint1 = binary.BigEndian.Uint32(payload[i : i+3])
	i += 3

	val.Switchpoint2 = binary.BigEndian.Uint32(payload[i : i+3])
	i += 3

	val.Switchpoint3 = binary.BigEndian.Uint32(payload[i : i+3])
	i += 3

	val.Switchpoint4 = binary.BigEndian.Uint32(payload[i : i+3])
	i += 3

	val.Switchpoint5 = binary.BigEndian.Uint32(payload[i : i+3])
	i += 3

	val.Switchpoint6 = binary.BigEndian.Uint32(payload[i : i+3])
	i += 3

	val.Switchpoint7 = binary.BigEndian.Uint32(payload[i : i+3])
	i += 3

	val.Switchpoint8 = binary.BigEndian.Uint32(payload[i : i+3])
	i += 3

	return val
}
