// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package scheduleentrylock

// <no value>

type ScheduleEntryLockYearDayGet struct {
	UserIdentifier byte

	ScheduleSlotId byte
}

func ParseScheduleEntryLockYearDayGet(payload []byte) ScheduleEntryLockYearDayGet {
	val := ScheduleEntryLockYearDayGet{}

	i := 2

	val.UserIdentifier = payload[i]
	i++

	val.ScheduleSlotId = payload[i]
	i++

	return val
}
