// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package zwaveplusinfo

import "errors"

// <no value>

type ZwaveplusInfoReport struct {
	ZWaveVersion byte

	RoleType byte

	NodeType byte
}

func (cmd *ZwaveplusInfoReport) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ZWaveVersion = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.RoleType = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NodeType = payload[i]
	i++

	return nil
}
