// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package zwaveplusinfo

// <no value>

type ZwaveplusInfoReport struct {
	ZWaveVersion byte

	RoleType byte

	NodeType byte
}

func ParseZwaveplusInfoReport(payload []byte) ZwaveplusInfoReport {
	val := ZwaveplusInfoReport{}

	i := 2

	val.ZWaveVersion = payload[i]
	i++

	val.RoleType = payload[i]
	i++

	val.NodeType = payload[i]
	i++

	return val
}
