// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package remoteassociation

// <no value>

type RemoteAssociationConfigurationSet struct {
	LocalGroupingIdentifier byte

	RemoteNodeid byte

	RemoteGroupingIdentifier byte
}

func ParseRemoteAssociationConfigurationSet(payload []byte) RemoteAssociationConfigurationSet {
	val := RemoteAssociationConfigurationSet{}

	i := 2

	val.LocalGroupingIdentifier = payload[i]
	i++

	val.RemoteNodeid = payload[i]
	i++

	val.RemoteGroupingIdentifier = payload[i]
	i++

	return val
}
