// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package remoteassociation

import "errors"

// <no value>

type RemoteAssociationConfigurationGet struct {
	LocalGroupingIdentifier byte
}

func (cmd *RemoteAssociationConfigurationGet) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.LocalGroupingIdentifier = payload[i]
	i++

	return nil
}

func (cmd *RemoteAssociationConfigurationGet) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.LocalGroupingIdentifier)

	return
}
