// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package remoteassociation

import "errors"

// <no value>

type RemoteAssociationConfigurationGet struct {
	LocalGroupingIdentifier byte
}

func (cmd *RemoteAssociationConfigurationGet) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.LocalGroupingIdentifier = payload[i]
	i++

	return nil
}
