// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package thermostatsetpointv2

// <no value>

type ThermostatSetpointSupportedGet struct {
}

func (cmd *ThermostatSetpointSupportedGet) UnmarshalBinary(payload []byte) error {

	return nil
}
