// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package antitheft

import "encoding/gob"

func init() {
	gob.Register(AntitheftGet{})
}

// <no value>
type AntitheftGet struct {
}

func (cmd *AntitheftGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)

	return nil
}

func (cmd *AntitheftGet) MarshalBinary() (payload []byte, err error) {

	return
}
