// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package antitheft

import (
	"encoding/binary"
	"errors"
)

// <no value>

type AntitheftReport struct {
	AntiTheftProtectionStatus byte

	ManufacturerId uint16

	AntiTheftHintNumberBytes byte

	AntiTheftHintByte []byte
}

func (cmd *AntitheftReport) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.AntiTheftProtectionStatus = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ManufacturerId = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.AntiTheftHintNumberBytes = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.AntiTheftHintByte = payload[i : i+2]
	i += 2

	return nil
}
