// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package schedule

import "errors"

// <no value>

type ScheduleRemove struct {
	ScheduleId byte
}

func (cmd *ScheduleRemove) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ScheduleId = payload[i]
	i++

	return nil
}

func (cmd *ScheduleRemove) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.ScheduleId)

	return
}
