// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package schedule

import (
	"encoding/binary"
	"errors"
)

// <no value>

type CommandScheduleReport struct {
	ScheduleId byte

	UserIdentifier byte

	StartYear byte

	Properties1 struct {
		StartMonth byte

		ActiveId byte
	}

	Properties2 struct {
		StartDayOfMonth byte
	}

	Properties3 struct {
		StartWeekday byte

		Res bool
	}

	Properties4 struct {
		StartHour byte

		DurationType byte
	}

	Properties5 struct {
		StartMinute byte
	}

	DurationByte uint16

	ReportsToFollow byte

	NumberOfCmdToFollow byte
}

func (cmd *CommandScheduleReport) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ScheduleId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.UserIdentifier = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.StartYear = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.StartMonth = (payload[i] & 0x0F)

	cmd.Properties1.ActiveId = (payload[i] & 0xF0) << 4

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties2.StartDayOfMonth = (payload[i] & 0x1F)

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties3.StartWeekday = (payload[i] & 0x7F)

	if payload[i]&0x80 == 0x80 {
		cmd.Properties3.Res = true
	} else {
		cmd.Properties3.Res = false
	}

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties4.StartHour = (payload[i] & 0x1F)

	cmd.Properties4.DurationType = (payload[i] & 0xE0) << 5

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties5.StartMinute = (payload[i] & 0x3F)

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.DurationByte = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ReportsToFollow = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NumberOfCmdToFollow = payload[i]
	i++

	return nil
}
