// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package schedule

import "errors"

// <no value>

type ScheduleStateSet struct {
	ScheduleId byte

	ScheduleState byte
}

func (cmd *ScheduleStateSet) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ScheduleId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ScheduleState = payload[i]
	i++

	return nil
}
