// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package schedule

// <no value>

type ScheduleStateReport struct {
	NumberOfSupportedScheduleId byte

	ReportsToFollow byte

	Override bool

	ActiveId1 byte

	ActiveId2 byte

	ActiveId3 byte

	ActiveIdN byte
}

func ParseScheduleStateReport(payload []byte) ScheduleStateReport {
	val := ScheduleStateReport{}

	i := 2

	val.NumberOfSupportedScheduleId = payload[i]
	i++

	val.ReportsToFollow = (payload[i] & 0xFE) << 1

	if payload[i]&0x01 == 0x01 {
		val.Override = true
	} else {
		val.Override = false
	}

	i += 1

	val.ActiveId1 = (payload[i] & 0x0F)

	val.ActiveId2 = (payload[i] & 0xF0) << 4

	i += 1

	val.ActiveId3 = (payload[i] & 0x0F)

	val.ActiveIdN = (payload[i] & 0xF0) << 4

	i += 1

	return val
}
