// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package schedule

import "encoding/gob"

func init() {
	gob.Register(ScheduleSupportedGet{})
}

// <no value>
type ScheduleSupportedGet struct {
}

func (cmd *ScheduleSupportedGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)

	return nil
}

func (cmd *ScheduleSupportedGet) MarshalBinary() (payload []byte, err error) {

	return
}
