// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package schedule

// <no value>

type ScheduleSupportedReport struct {
	NumberOfSupportedScheduleId byte

	StartTimeSupport byte

	FallbackSupport bool

	SupportEnabledisable bool

	NumberOfSupportedCc byte

	SupportedOverrideTypes byte

	OverrideSupport bool
}

func ParseScheduleSupportedReport(payload []byte) ScheduleSupportedReport {
	val := ScheduleSupportedReport{}

	i := 2

	val.NumberOfSupportedScheduleId = payload[i]
	i++

	val.StartTimeSupport = (payload[i] & 0x3F)

	if payload[i]&0x40 == 0x40 {
		val.FallbackSupport = true
	} else {
		val.FallbackSupport = false
	}

	if payload[i]&0x80 == 0x80 {
		val.SupportEnabledisable = true
	} else {
		val.SupportEnabledisable = false
	}

	i += 1

	val.NumberOfSupportedCc = payload[i]
	i++

	val.SupportedOverrideTypes = (payload[i] & 0x7F)

	if payload[i]&0x80 == 0x80 {
		val.OverrideSupport = true
	} else {
		val.OverrideSupport = false
	}

	i += 1

	return val
}
