// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package thermostatheating

// <no value>

type ThermostatHeatingModeReport struct {
	Mode byte
}

func ParseThermostatHeatingModeReport(payload []byte) ThermostatHeatingModeReport {
	val := ThermostatHeatingModeReport{}

	i := 2

	val.Mode = payload[i]
	i++

	return val
}
