// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package thermostatheating

import "encoding/gob"

func init() {
	gob.Register(ThermostatHeatingRelayStatusGet{})
}

// <no value>
type ThermostatHeatingRelayStatusGet struct {
}

func (cmd *ThermostatHeatingRelayStatusGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)

	return nil
}

func (cmd *ThermostatHeatingRelayStatusGet) MarshalBinary() (payload []byte, err error) {

	return
}
