// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package thermostatheating

// <no value>

type ThermostatHeatingSetpointReport struct {
	SetpointNr byte

	Properties1 struct {
		Size byte

		Scale byte

		Precision byte
	}

	Value []byte
}

func ParseThermostatHeatingSetpointReport(payload []byte) ThermostatHeatingSetpointReport {
	val := ThermostatHeatingSetpointReport{}

	i := 2

	val.SetpointNr = payload[i]
	i++

	val.Properties1.Size = (payload[i] & 0x07)

	val.Properties1.Scale = (payload[i] & 0x18) << 3

	val.Properties1.Precision = (payload[i] & 0xE0) << 5

	i += 1

	val.Value = payload[i : i+1]
	i += 1

	return val
}
