// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package thermostatheating

// <no value>

type ThermostatHeatingSetpointGet struct {
	SetpointNr byte
}

func ParseThermostatHeatingSetpointGet(payload []byte) ThermostatHeatingSetpointGet {
	val := ThermostatHeatingSetpointGet{}

	i := 2

	val.SetpointNr = payload[i]
	i++

	return val
}
