// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package thermostatheating

import "errors"

// <no value>

type ThermostatHeatingTimedOffSet struct {
	Minutes byte

	Hours byte
}

func (cmd *ThermostatHeatingTimedOffSet) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Minutes = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Hours = payload[i]
	i++

	return nil
}
