// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package firmwareupdatemd

// <no value>

type FirmwareMdGet struct {
}

func (cmd *FirmwareMdGet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *FirmwareMdGet) MarshalBinary() (payload []byte, err error) {

	return
}
