// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package firmwareupdatemd

import (
	"encoding/gob"
	"errors"
)

func init() {
	gob.Register(FirmwareUpdateMdReport{})
}

// <no value>
type FirmwareUpdateMdReport struct {
	Properties1 struct {
		ReportNumber1 byte

		Last bool
	}

	ReportNumber2 byte

	Data []byte
}

func (cmd *FirmwareUpdateMdReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.ReportNumber1 = (payload[i] & 0x7F)

	if payload[i]&0x80 == 0x80 {
		cmd.Properties1.Last = true
	} else {
		cmd.Properties1.Last = false
	}

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ReportNumber2 = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Data = payload[i:]

	return nil
}

func (cmd *FirmwareUpdateMdReport) MarshalBinary() (payload []byte, err error) {

	{
		var val byte

		val |= (cmd.Properties1.ReportNumber1) & byte(0x7F)

		if cmd.Properties1.Last {
			val |= byte(0x80) // flip bits on
		} else {
			val &= ^byte(0x80) // flip bits off
		}

		payload = append(payload, val)
	}

	payload = append(payload, cmd.ReportNumber2)

	payload = append(payload, cmd.Data...)

	return
}
