// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package firmwareupdatemd

import "errors"

// <no value>

type FirmwareUpdateMdRequestReport struct {
	Status byte
}

func (cmd *FirmwareUpdateMdRequestReport) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Status = payload[i]
	i++

	return nil
}

func (cmd *FirmwareUpdateMdRequestReport) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.Status)

	return
}
