// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package meterv4

import "encoding/binary"

// <no value>

type MeterReport struct {
	Properties1 struct {
		Scale2 bool

		MeterType byte

		RateType byte
	}

	Properties2 struct {
		Size byte

		Scale10 byte

		Precision byte
	}

	MeterValue []byte

	DeltaTime uint16

	PreviousMeterValue []byte

	Scale2 byte
}

func ParseMeterReport(payload []byte) MeterReport {
	val := MeterReport{}

	i := 2

	val.Properties1.MeterType = (payload[i] & 0x1F)

	val.Properties1.RateType = (payload[i] & 0x60) << 5

	if payload[i]&0x80 == 0x80 {
		val.Properties1.Scale2 = true
	} else {
		val.Properties1.Scale2 = false
	}

	i += 1

	val.Properties2.Size = (payload[i] & 0x07)

	val.Properties2.Scale10 = (payload[i] & 0x18) << 3

	val.Properties2.Precision = (payload[i] & 0xE0) << 5

	i += 1

	val.MeterValue = payload[i : i+1]
	i += 1

	val.DeltaTime = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	val.PreviousMeterValue = payload[i : i+1]
	i += 1

	val.Scale2 = payload[i]
	i++

	return val
}
