// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package meterv4

import "encoding/binary"

// <no value>

type MeterReport struct {
	Scale2 bool

	MeterType byte

	RateType byte

	Size byte

	Scale10 byte

	Precision byte

	MeterValue []byte

	DeltaTime uint16

	PreviousMeterValue []byte

	Scale2 byte
}

func ParseMeterReport(payload []byte) MeterReport {
	val := MeterReport{}

	i := 2

	val.MeterType = (payload[i] & 0x1F)

	val.RateType = (payload[i] & 0x60) << 5

	if payload[i]&0x80 == 0x80 {
		val.Scale2 = true
	} else {
		val.Scale2 = false
	}

	i += 1

	val.Size = (payload[i] & 0x07)

	val.Scale10 = (payload[i] & 0x18) << 3

	val.Precision = (payload[i] & 0xE0) << 5

	i += 1

	val.MeterValue = payload[i : i+1]
	i += 1

	val.DeltaTime = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	val.PreviousMeterValue = payload[i : i+1]
	i += 1

	val.Scale2 = payload[i]
	i++

	return val
}
