// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package versionv2

// <no value>

type VersionGet struct {
}

func ParseVersionGet(payload []byte) VersionGet {
	val := VersionGet{}

	return val
}
