// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package battery

// <no value>

type BatteryGet struct {
}

func (cmd *BatteryGet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *BatteryGet) MarshalBinary() (payload []byte, err error) {

	return
}
