// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package battery

import "errors"

// <no value>

type BatteryReport struct {
	BatteryLevel byte
}

func (cmd *BatteryReport) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.BatteryLevel = payload[i]
	i++

	return nil
}

func (cmd *BatteryReport) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.BatteryLevel)

	return
}
