// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package energyproduction

import "errors"

// <no value>

type EnergyProductionGet struct {
	ParameterNumber byte
}

func (cmd *EnergyProductionGet) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ParameterNumber = payload[i]
	i++

	return nil
}

func (cmd *EnergyProductionGet) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.ParameterNumber)

	return
}
