// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package energyproduction

import "errors"

// <no value>

type EnergyProductionGet struct {
	ParameterNumber byte
}

func (cmd *EnergyProductionGet) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ParameterNumber = payload[i]
	i++

	return nil
}
