// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package energyproduction

import "errors"

// <no value>

type EnergyProductionReport struct {
	ParameterNumber byte

	Level struct {
		Size byte

		Scale byte

		Precision byte
	}

	Value []byte
}

func (cmd *EnergyProductionReport) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ParameterNumber = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Level.Size = (payload[i] & 0x07)

	cmd.Level.Scale = (payload[i] & 0x18) << 3

	cmd.Level.Precision = (payload[i] & 0xE0) << 5

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Value = payload[i : i+1]
	i += 1

	return nil
}
