// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package energyproduction

// <no value>

type EnergyProductionReport struct {
	ParameterNumber byte

	Level struct {
		Size byte

		Scale byte

		Precision byte
	}

	Value []byte
}

func ParseEnergyProductionReport(payload []byte) EnergyProductionReport {
	val := EnergyProductionReport{}

	i := 2

	val.ParameterNumber = payload[i]
	i++

	val.Level.Size = (payload[i] & 0x07)

	val.Level.Scale = (payload[i] & 0x18) << 3

	val.Level.Precision = (payload[i] & 0xE0) << 5

	i += 1

	val.Value = payload[i : i+1]
	i += 1

	return val
}
