// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package configurationv2

import "encoding/binary"

// <no value>

type ConfigurationBulkGet struct {
	ParameterOffset uint16

	NumberOfParameters byte
}

func ParseConfigurationBulkGet(payload []byte) ConfigurationBulkGet {
	val := ConfigurationBulkGet{}

	i := 2

	val.ParameterOffset = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	val.NumberOfParameters = payload[i]
	i++

	return val
}
