// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package networkmanagementbasic

// <no value>

type DefaultSet struct {
	SeqNo byte
}

func ParseDefaultSet(payload []byte) DefaultSet {
	val := DefaultSet{}

	i := 2

	val.SeqNo = payload[i]
	i++

	return val
}
