// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package networkmanagementbasic

// <no value>

type NetworkUpdateRequestStatus struct {
	SeqNo byte

	Status byte
}

func ParseNetworkUpdateRequestStatus(payload []byte) NetworkUpdateRequestStatus {
	val := NetworkUpdateRequestStatus{}

	i := 2

	val.SeqNo = payload[i]
	i++

	val.Status = payload[i]
	i++

	return val
}
