// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package screenmd

// <no value>

type ScreenMdReport struct {
	CharPresentation byte

	ScreenSettings byte

	MoreData bool
}

func ParseScreenMdReport(payload []byte) ScreenMdReport {
	val := ScreenMdReport{}

	i := 2

	val.CharPresentation = (payload[i] & 0x07)

	val.ScreenSettings = (payload[i] & 0x38) << 3

	if payload[i]&0x80 == 0x80 {
		val.MoreData = true
	} else {
		val.MoreData = false
	}

	i += 1

	return val
}
