// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package sensorbinaryv2

import "errors"

// <no value>

type SensorBinarySupportedSensorReport struct {
	BitMask byte
}

func (cmd *SensorBinarySupportedSensorReport) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.BitMask = payload[i]
	i++

	return nil
}

func (cmd *SensorBinarySupportedSensorReport) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.BitMask)

	return
}
