// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package tarifftblmonitor

import (
	"encoding/binary"
	"errors"
)

// <no value>

type TariffTblReport struct {
	RateParameterSetId byte

	Properties1 struct {
		TariffPrecision byte
	}

	TariffValue uint32
}

func (cmd *TariffTblReport) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.RateParameterSetId = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.TariffPrecision = (payload[i] & 0xE0) >> 5

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.TariffValue = binary.BigEndian.Uint32(payload[i : i+4])
	i += 4

	return nil
}

func (cmd *TariffTblReport) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.RateParameterSetId)

	{
		var val byte

		val |= (cmd.Properties1.TariffPrecision << byte(5)) & byte(0xE0)

		payload = append(payload, val)
	}

	{
		buf := make([]byte, 4)
		binary.BigEndian.PutUint32(buf, cmd.TariffValue)
		payload = append(payload, buf...)
	}

	return
}
