// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package sensormultilevelv6

import (
	"encoding/gob"
	"errors"
)

func init() {
	gob.Register(SupportedGetScale{})
}

// <no value>
type SupportedGetScale struct {
	SensorType byte
}

func (cmd SupportedGetScale) CommandClassID() byte {
	return 0x31
}

func (cmd SupportedGetScale) CommandID() byte {
	return byte(CommandSupportedGetScale)
}

func (cmd *SupportedGetScale) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SensorType = payload[i]
	i++

	return nil
}

func (cmd *SupportedGetScale) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = cmd.CommandClassID()
	payload[1] = cmd.CommandID()

	payload = append(payload, cmd.SensorType)

	return
}
