// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package firmwareupdatemdv2

// <no value>

type FirmwareMdGet struct {
}

func (cmd *FirmwareMdGet) UnmarshalBinary(payload []byte) error {

	return nil
}
