// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package firmwareupdatemdv2

import "errors"

// <no value>

type FirmwareUpdateMdStatusReport struct {
	Status byte
}

func (cmd *FirmwareUpdateMdStatusReport) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Status = payload[i]
	i++

	return nil
}
