// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package wakeup

// <no value>

type WakeUpIntervalGet struct {
}

func ParseWakeUpIntervalGet(payload []byte) WakeUpIntervalGet {
	val := WakeUpIntervalGet{}

	return val
}
