// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package wakeup

// <no value>

type WakeUpNotification struct {
}

func (cmd *WakeUpNotification) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *WakeUpNotification) MarshalBinary() (payload []byte, err error) {

	return
}
