// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package alarm

// <no value>

type AlarmGet struct {
	AlarmType byte
}

func ParseAlarmGet(payload []byte) AlarmGet {
	val := AlarmGet{}

	i := 2

	val.AlarmType = payload[i]
	i++

	return val
}
