// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package securitypanelzone

// <no value>

type SecurityPanelZoneNumberSupportedGet struct {
}

func (cmd *SecurityPanelZoneNumberSupportedGet) UnmarshalBinary(payload []byte) error {

	return nil
}
