// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package securitypanelzone

// <no value>

type SecurityPanelZoneStateReport struct {
	ZoneNumber byte

	ZoneState byte
}

func ParseSecurityPanelZoneStateReport(payload []byte) SecurityPanelZoneStateReport {
	val := SecurityPanelZoneStateReport{}

	i := 2

	val.ZoneNumber = payload[i]
	i++

	val.ZoneState = payload[i]
	i++

	return val
}
