// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package securitypanelzone

// <no value>

type SecurityPanelZoneStateGet struct {
	ZoneNumber byte
}

func ParseSecurityPanelZoneStateGet(payload []byte) SecurityPanelZoneStateGet {
	val := SecurityPanelZoneStateGet{}

	i := 2

	val.ZoneNumber = payload[i]
	i++

	return val
}
