// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package securitypanelzone

import (
	"encoding/gob"
	"errors"
)

func init() {
	gob.Register(SecurityPanelZoneStateGet{})
}

// <no value>
type SecurityPanelZoneStateGet struct {
	ZoneNumber byte
}

func (cmd *SecurityPanelZoneStateGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ZoneNumber = payload[i]
	i++

	return nil
}

func (cmd *SecurityPanelZoneStateGet) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.ZoneNumber)

	return
}
