// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package doorlock

import "errors"

// <no value>

type DoorLockOperationSet struct {
	DoorLockMode byte
}

func (cmd *DoorLockOperationSet) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.DoorLockMode = payload[i]
	i++

	return nil
}
