// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package doorlock

import "encoding/gob"

func init() {
	gob.Register(OperationGet{})
}

// <no value>
type OperationGet struct {
}

func (cmd OperationGet) CommandClassID() byte {
	return 0x62
}

func (cmd OperationGet) CommandID() byte {
	return byte(CommandOperationGet)
}

func (cmd *OperationGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *OperationGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = cmd.CommandClassID()
	payload[1] = cmd.CommandID()

	return
}
