// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package doorlock

// <no value>

type DoorLockOperationGet struct {
}

func (cmd *DoorLockOperationGet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *DoorLockOperationGet) MarshalBinary() (payload []byte, err error) {

	return
}
