// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package timev2

// <no value>

type TimeOffsetGet struct {
}

func (cmd *TimeOffsetGet) UnmarshalBinary(payload []byte) error {

	return nil
}
