// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package language

// <no value>

type LanguageGet struct {
}

func ParseLanguageGet(payload []byte) LanguageGet {
	val := LanguageGet{}

	return val
}
