// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package doorlockv2

import "encoding/gob"

func init() {
	gob.Register(ConfigurationGet{})
}

// <no value>
type ConfigurationGet struct {
}

func (cmd ConfigurationGet) CommandClassID() byte {
	return 0x62
}

func (cmd ConfigurationGet) CommandID() byte {
	return byte(CommandConfigurationGet)
}

func (cmd *ConfigurationGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *ConfigurationGet) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = cmd.CommandClassID()
	payload[1] = cmd.CommandID()

	return
}
