// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package timeparameters

// <no value>

type TimeParametersGet struct {
}

func ParseTimeParametersGet(payload []byte) TimeParametersGet {
	val := TimeParametersGet{}

	return val
}
