// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package timeparameters

// <no value>

type TimeParametersGet struct {
}

func (cmd *TimeParametersGet) UnmarshalBinary(payload []byte) error {

	return nil
}
