// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package tariffconfig

// <no value>

type TariffTblRemove struct {
	RateParameterSetIds byte

	RateParameterSetId []byte
}

func ParseTariffTblRemove(payload []byte) TariffTblRemove {
	val := TariffTblRemove{}

	i := 2

	val.RateParameterSetIds = (payload[i] & 0x3F)

	i += 1

	val.RateParameterSetId = payload[i : i+0]
	i += 0

	return val
}
