// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package groupingname

// <no value>

type GroupingNameSet struct {
	GroupingIdentifier byte

	CharPresentation byte

	GroupingName string
}

func ParseGroupingNameSet(payload []byte) GroupingNameSet {
	val := GroupingNameSet{}

	i := 2

	val.GroupingIdentifier = payload[i]
	i++

	val.CharPresentation = (payload[i] & 0x07)

	i += 1

	val.GroupingName = string(payload[i : i+16])

	i += 16

	return val
}
