// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package multiinstance

import "errors"

// <no value>

type MultiInstanceCmdEncap struct {
	Instance byte

	CommandClass byte

	Command byte

	Parameter []byte
}

func (cmd *MultiInstanceCmdEncap) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Instance = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.CommandClass = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Command = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Parameter = payload[i:]

	return nil
}

func (cmd *MultiInstanceCmdEncap) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.Instance)

	payload = append(payload, cmd.CommandClass)

	payload = append(payload, cmd.Command)

	payload = append(payload, cmd.Parameter...)

	return
}
