// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package multiinstance

// <no value>

type MultiInstanceCmdEncap struct {
	Instance byte

	CommandClass byte

	Command byte

	Parameter []byte
}

func ParseMultiInstanceCmdEncap(payload []byte) MultiInstanceCmdEncap {
	val := MultiInstanceCmdEncap{}

	i := 2

	val.Instance = payload[i]
	i++

	val.CommandClass = payload[i]
	i++

	val.Command = payload[i]
	i++

	val.Parameter = payload[i:]

	return val
}
