// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package multiinstance

import "errors"

// <no value>

type MultiInstanceReport struct {
	CommandClass byte

	Instances byte
}

func (cmd *MultiInstanceReport) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.CommandClass = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Instances = payload[i]
	i++

	return nil
}
