// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package meter

// <no value>

type MeterReport struct {
	MeterType byte

	Properties1 struct {
		Size byte

		Scale byte

		Precision byte
	}

	MeterValue []byte
}

func ParseMeterReport(payload []byte) MeterReport {
	val := MeterReport{}

	i := 2

	val.MeterType = payload[i]
	i++

	val.Properties1.Size = (payload[i] & 0x07)

	val.Properties1.Scale = (payload[i] & 0x18) << 3

	val.Properties1.Precision = (payload[i] & 0xE0) << 5

	i += 1

	val.MeterValue = payload[i : i+1]
	i += 1

	return val
}
