// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package metertblmonitor

import "encoding/binary"

// <no value>

type MeterTblReport struct {
	MeterType byte

	RateType byte

	PayMeter byte

	DatasetSupported uint32

	DatasetHistorySupported uint32

	DataHistorySupported uint32
}

func ParseMeterTblReport(payload []byte) MeterTblReport {
	val := MeterTblReport{}

	i := 2

	val.MeterType = (payload[i] & 0x3F)

	val.RateType = (payload[i] & 0xC0) << 6

	i += 1

	val.PayMeter = (payload[i] & 0x0F)

	i += 1

	val.DatasetSupported = binary.BigEndian.Uint32(payload[i : i+3])
	i += 3

	val.DatasetHistorySupported = binary.BigEndian.Uint32(payload[i : i+3])
	i += 3

	val.DataHistorySupported = binary.BigEndian.Uint32(payload[i : i+3])
	i += 3

	return val
}
