// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package metertblmonitor

import (
	"encoding/gob"
	"errors"
)

func init() {
	gob.Register(MeterTblStatusDepthGet{})
}

// <no value>
type MeterTblStatusDepthGet struct {
	StatusEventLogDepth byte
}

func (cmd *MeterTblStatusDepthGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.StatusEventLogDepth = payload[i]
	i++

	return nil
}

func (cmd *MeterTblStatusDepthGet) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.StatusEventLogDepth)

	return
}
