// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package metertblmonitor

import "encoding/gob"

func init() {
	gob.Register(MeterTblTableIdGet{})
}

// <no value>
type MeterTblTableIdGet struct {
}

func (cmd *MeterTblTableIdGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)

	return nil
}

func (cmd *MeterTblTableIdGet) MarshalBinary() (payload []byte, err error) {

	return
}
