// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package metertblmonitor

// <no value>

type MeterTblTableCapabilityGet struct {
}

func ParseMeterTblTableCapabilityGet(payload []byte) MeterTblTableCapabilityGet {
	val := MeterTblTableCapabilityGet{}

	return val
}
