// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package metertblmonitor

import "encoding/binary"

// <no value>

type MeterTblHistoricalDataReport struct {
	ReportsToFollow byte

	RateType byte

	Dataset uint32

	Year uint16

	Month byte

	Day byte

	HourLocalTime byte

	MinuteLocalTime byte

	SecondLocalTime byte
}

func ParseMeterTblHistoricalDataReport(payload []byte) MeterTblHistoricalDataReport {
	val := MeterTblHistoricalDataReport{}

	i := 2

	val.ReportsToFollow = payload[i]
	i++

	val.RateType = (payload[i] & 0x03)

	i += 1

	val.Dataset = binary.BigEndian.Uint32(payload[i : i+3])
	i += 3

	val.Year = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	val.Month = payload[i]
	i++

	val.Day = payload[i]
	i++

	val.HourLocalTime = payload[i]
	i++

	val.MinuteLocalTime = payload[i]
	i++

	val.SecondLocalTime = payload[i]
	i++

	return val
}
