// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package prepayment

import "errors"

// <no value>

type PrepaymentBalanceGet struct {
	Properties1 struct {
		BalanceType byte
	}
}

func (cmd *PrepaymentBalanceGet) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.BalanceType = (payload[i] & 0xC0) >> 6

	i += 1

	return nil
}

func (cmd *PrepaymentBalanceGet) MarshalBinary() (payload []byte, err error) {

	{
		var val byte

		val |= (cmd.Properties1.BalanceType << byte(6)) & byte(0xC0)

		payload = append(payload, val)
	}

	return
}
