// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package security

import (
	"encoding/gob"
	"errors"
)

func init() {
	gob.Register(NetworkKeySet{})
}

// <no value>
type NetworkKeySet struct {
	NetworkKeyByte []byte
}

func (cmd *NetworkKeySet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NetworkKeyByte = payload[i:]

	return nil
}

func (cmd *NetworkKeySet) MarshalBinary() (payload []byte, err error) {

	payload = append(payload, cmd.NetworkKeyByte...)

	return
}
