// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package security

import (
	"encoding/gob"
	"errors"
)

func init() {
	gob.Register(NonceReport{})
}

// <no value>
type NonceReport struct {
	NonceByte []byte
}

func (cmd NonceReport) CommandClassID() byte {
	return 0x98
}

func (cmd NonceReport) CommandID() byte {
	return byte(CommandNonceReport)
}

func (cmd *NonceReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.NonceByte = payload[i : i+8]

	i += 8

	return nil
}

func (cmd *NonceReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = cmd.CommandClassID()
	payload[1] = cmd.CommandID()

	if paramLen := len(cmd.NonceByte); paramLen > 8 {
		return nil, errors.New("Length overflow in array parameter NonceByte")
	}

	payload = append(payload, cmd.NonceByte...)

	return
}
