// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package security

// <no value>

type SecurityNonceGet struct {
}

func ParseSecurityNonceGet(payload []byte) SecurityNonceGet {
	val := SecurityNonceGet{}

	return val
}
