// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package security

// <no value>

type SecuritySchemeGet struct {
	SupportedSecuritySchemes byte
}

func ParseSecuritySchemeGet(payload []byte) SecuritySchemeGet {
	val := SecuritySchemeGet{}

	i := 2

	val.SupportedSecuritySchemes = payload[i]
	i++

	return val
}
