// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package thermostatmodev2

// <no value>

type ThermostatModeGet struct {
}

func ParseThermostatModeGet(payload []byte) ThermostatModeGet {
	val := ThermostatModeGet{}

	return val
}
