// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package thermostatmodev2

// <no value>

type ThermostatModeSupportedGet struct {
}

func ParseThermostatModeSupportedGet(payload []byte) ThermostatModeSupportedGet {
	val := ThermostatModeSupportedGet{}

	return val
}
