// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package basicwindowcovering

import "errors"

// <no value>

type BasicWindowCoveringStartLevelChange struct {
	Level struct {
		OpenClose bool
	}
}

func (cmd *BasicWindowCoveringStartLevelChange) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	if payload[i]&0x40 == 0x40 {
		cmd.Level.OpenClose = true
	} else {
		cmd.Level.OpenClose = false
	}

	i += 1

	return nil
}
