// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package basicwindowcovering

// <no value>

type BasicWindowCoveringStartLevelChange struct {
	OpenClose bool
}

func ParseBasicWindowCoveringStartLevelChange(payload []byte) BasicWindowCoveringStartLevelChange {
	val := BasicWindowCoveringStartLevelChange{}

	i := 2

	if payload[i]&0x40 == 0x40 {
		val.OpenClose = true
	} else {
		val.OpenClose = false
	}

	i += 1

	return val
}
