// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package applicationstatus

// <no value>

type ApplicationBusy struct {
	Status byte

	WaitTime byte
}

func ParseApplicationBusy(payload []byte) ApplicationBusy {
	val := ApplicationBusy{}

	i := 2

	val.Status = payload[i]
	i++

	val.WaitTime = payload[i]
	i++

	return val
}
