// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package ratetblmonitor

// <no value>

type RateTblActiveRateGet struct {
}

func ParseRateTblActiveRateGet(payload []byte) RateTblActiveRateGet {
	val := RateTblActiveRateGet{}

	return val
}
