// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package ratetblmonitor

// <no value>

type RateTblGet struct {
	RateParameterSetId byte
}

func ParseRateTblGet(payload []byte) RateTblGet {
	val := RateTblGet{}

	i := 2

	val.RateParameterSetId = payload[i]
	i++

	return val
}
