// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package wakeupv2

// <no value>

type WakeUpIntervalCapabilitiesGet struct {
}

func ParseWakeUpIntervalCapabilitiesGet(payload []byte) WakeUpIntervalCapabilitiesGet {
	val := WakeUpIntervalCapabilitiesGet{}

	return val
}
