// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package wakeupv2

// <no value>

type WakeUpNoMoreInformation struct {
}

func ParseWakeUpNoMoreInformation(payload []byte) WakeUpNoMoreInformation {
	val := WakeUpNoMoreInformation{}

	return val
}
