// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package firmwareupdatemdv3

import "encoding/binary"

// <no value>

type FirmwareMdReport struct {
	ManufacturerId uint16

	Firmware0Id uint16

	Firmware0Checksum uint16

	FirmwareUpgradable byte

	NumberOfFirmwareTargets byte

	MaxFragmentSize uint16
}

func ParseFirmwareMdReport(payload []byte) FirmwareMdReport {
	val := FirmwareMdReport{}

	i := 2

	val.ManufacturerId = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	val.Firmware0Id = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	val.Firmware0Checksum = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	val.FirmwareUpgradable = payload[i]
	i++

	val.NumberOfFirmwareTargets = payload[i]
	i++

	val.MaxFragmentSize = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	return val
}
