// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package firmwareupdatemdv3

// <no value>

type FirmwareUpdateMdGet struct {
	NumberOfReports byte

	Properties1 struct {
		ReportNumber1 byte

		Zero bool
	}

	ReportNumber2 byte
}

func ParseFirmwareUpdateMdGet(payload []byte) FirmwareUpdateMdGet {
	val := FirmwareUpdateMdGet{}

	i := 2

	val.NumberOfReports = payload[i]
	i++

	val.Properties1.ReportNumber1 = (payload[i] & 0x7F)

	if payload[i]&0x80 == 0x80 {
		val.Properties1.Zero = true
	} else {
		val.Properties1.Zero = false
	}

	i += 1

	val.ReportNumber2 = payload[i]
	i++

	return val
}
