// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package firmwareupdatemdv3

// <no value>

type FirmwareUpdateMdRequestReport struct {
	Status byte
}

func ParseFirmwareUpdateMdRequestReport(payload []byte) FirmwareUpdateMdRequestReport {
	val := FirmwareUpdateMdRequestReport{}

	i := 2

	val.Status = payload[i]
	i++

	return val
}
