// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package firmwareupdatemdv3

import (
	"encoding/binary"
	"errors"
)

// <no value>

type FirmwareUpdateMdRequestGet struct {
	ManufacturerId uint16

	FirmwareId uint16

	Checksum uint16

	FirmwareTarget byte

	FragmentSize uint16
}

func (cmd *FirmwareUpdateMdRequestGet) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ManufacturerId = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.FirmwareId = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Checksum = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.FirmwareTarget = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.FragmentSize = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	return nil
}
