// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package firmwareupdatemdv3

import (
	"encoding/binary"
	"errors"
)

// <no value>

type FirmwareUpdateMdStatusReport struct {
	Status byte

	Waittime uint16
}

func (cmd *FirmwareUpdateMdStatusReport) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Status = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Waittime = binary.BigEndian.Uint16(payload[i : i+2])
	i += 2

	return nil
}
