// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package thermostatsetback

// <no value>

type ThermostatSetbackReport struct {
	Properties1 struct {
		SetbackType byte
	}

	SetbackState byte
}

func ParseThermostatSetbackReport(payload []byte) ThermostatSetbackReport {
	val := ThermostatSetbackReport{}

	i := 2

	val.Properties1.SetbackType = (payload[i] & 0x03)

	i += 1

	val.SetbackState = payload[i]
	i++

	return val
}
