// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package thermostatsetback

import (
	"encoding/gob"
	"errors"
)

func init() {
	gob.Register(ThermostatSetbackSet{})
}

// <no value>
type ThermostatSetbackSet struct {
	Properties1 struct {
		SetbackType byte
	}

	SetbackState byte
}

func (cmd *ThermostatSetbackSet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.SetbackType = (payload[i] & 0x03)

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SetbackState = payload[i]
	i++

	return nil
}

func (cmd *ThermostatSetbackSet) MarshalBinary() (payload []byte, err error) {

	{
		var val byte

		val |= (cmd.Properties1.SetbackType) & byte(0x03)

		payload = append(payload, val)
	}

	payload = append(payload, cmd.SetbackState)

	return
}
