// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package centralscene

import "errors"

// <no value>

type CentralSceneNotification struct {
	SequenceNumber byte

	Properties1 struct {
		KeyAttributes byte
	}

	SceneNumber byte
}

func (cmd *CentralSceneNotification) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SequenceNumber = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.KeyAttributes = (payload[i] & 0x07)

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.SceneNumber = payload[i]
	i++

	return nil
}
