// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package centralscene

import "encoding/gob"

func init() {
	gob.Register(CentralSceneSupportedGet{})
}

// <no value>
type CentralSceneSupportedGet struct {
}

func (cmd *CentralSceneSupportedGet) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning
	payload := make([]byte, len(data))
	copy(payload, data)

	return nil
}

func (cmd *CentralSceneSupportedGet) MarshalBinary() (payload []byte, err error) {

	return
}
