// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package centralscene

// <no value>

type CentralSceneSupportedGet struct {
}

func (cmd *CentralSceneSupportedGet) UnmarshalBinary(payload []byte) error {

	return nil
}

func (cmd *CentralSceneSupportedGet) MarshalBinary() (payload []byte, err error) {

	return
}
