// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package mtpwindowcovering

// <no value>

type MoveToPositionGet struct {
}

func ParseMoveToPositionGet(payload []byte) MoveToPositionGet {
	val := MoveToPositionGet{}

	return val
}
