// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package versionv2

import (
	"encoding/gob"
	"errors"
)

func init() {
	gob.Register(CommandClassReport{})
}

// <no value>
type CommandClassReport struct {
	RequestedCommandClass byte

	CommandClassVersion byte
}

func (cmd CommandClassReport) CommandClassID() byte {
	return 0x86
}

func (cmd CommandClassReport) CommandID() byte {
	return byte(CommandCommandClassReport)
}

func (cmd *CommandClassReport) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	payload := make([]byte, len(data))
	copy(payload, data)

	if len(payload) < 2 {
		return errors.New("Payload length underflow")
	}

	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.RequestedCommandClass = payload[i]
	i++

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.CommandClassVersion = payload[i]
	i++

	return nil
}

func (cmd *CommandClassReport) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = cmd.CommandClassID()
	payload[1] = cmd.CommandID()

	payload = append(payload, cmd.RequestedCommandClass)

	payload = append(payload, cmd.CommandClassVersion)

	return
}
