// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package meterv3

// <no value>

type MeterGet struct {
	Properties1 struct {
		Scale byte
	}
}

func ParseMeterGet(payload []byte) MeterGet {
	val := MeterGet{}

	i := 2

	val.Properties1.Scale = (payload[i] & 0x38) << 3

	i += 1

	return val
}
