// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package meterv3

import "errors"

// <no value>

type MeterGet struct {
	Properties1 struct {
		Scale byte
	}
}

func (cmd *MeterGet) UnmarshalBinary(payload []byte) error {
	i := 0

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.Scale = (payload[i] & 0x38) >> 3

	i += 1

	return nil
}

func (cmd *MeterGet) MarshalBinary() (payload []byte, err error) {

	{
		var val byte

		val |= (cmd.Properties1.Scale << byte(3)) & byte(0x38)

		payload = append(payload, val)
	}

	return
}
