// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package meterv3

import "errors"

// <no value>

type MeterSupportedReport struct {
	Properties1 struct {
		MeterType byte

		MeterReset bool
	}

	ScaleSupported byte
}

func (cmd *MeterSupportedReport) UnmarshalBinary(payload []byte) error {
	i := 2

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.Properties1.MeterType = (payload[i] & 0x1F)

	if payload[i]&0x80 == 0x80 {
		cmd.Properties1.MeterReset = true
	} else {
		cmd.Properties1.MeterReset = false
	}

	i += 1

	if len(payload) <= i {
		return errors.New("slice index out of bounds")
	}

	cmd.ScaleSupported = payload[i]
	i++

	return nil
}
