// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package meterv3

// <no value>

type MeterSupportedReport struct {
	MeterType byte

	MeterReset bool

	ScaleSupported byte
}

func ParseMeterSupportedReport(payload []byte) MeterSupportedReport {
	val := MeterSupportedReport{}

	i := 2

	val.MeterType = (payload[i] & 0x1F)

	if payload[i]&0x80 == 0x80 {
		val.MeterReset = true
	} else {
		val.MeterReset = false
	}

	i += 1

	val.ScaleSupported = payload[i]
	i++

	return val
}
