// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package zensornet

// <no value>

type BindAccept struct {
}

func ParseBindAccept(payload []byte) BindAccept {
	val := BindAccept{}

	return val
}
