// THIS FILE IS AUTO-GENERATED BY CCGEN
// DO NOT MODIFY

package switchtogglebinary

import (
	"encoding/gob"

	"github.com/helioslabs/gozw/command-class"
)

const CommandSet commandclass.CommandID = 0x01

func init() {
	gob.Register(Set{})
	commandclass.Register(commandclass.CommandIdentifier{
		CommandClass: commandclass.CommandClassID(0x28),
		Command:      commandclass.CommandID(0x01),
		Version:      1,
	}, NewSet)
}

func NewSet() commandclass.Command {
	return &Set{}
}

// <no value>
type Set struct {
}

func (cmd Set) CommandClassID() commandclass.CommandClassID {
	return 0x28
}

func (cmd Set) CommandID() commandclass.CommandID {
	return CommandSet
}

func (cmd Set) CommandIDString() string {
	return "SWITCH_TOGGLE_BINARY_SET"
}

func (cmd *Set) UnmarshalBinary(data []byte) error {
	// According to the docs, we must copy data if we wish to retain it after returning

	return nil
}

func (cmd *Set) MarshalBinary() (payload []byte, err error) {
	payload = make([]byte, 2)
	payload[0] = byte(cmd.CommandClassID())
	payload[1] = byte(cmd.CommandID())

	return
}
